### ISSUE TITLE
Support file-like objects in fiona.open()

### ISSUE THREAD

**Issue by timtroendle** [Toblerity/Fiona#409] opened 2017-01-13 14:42 UTC
If `fiona.open()` was accepting file-like objects instead of solely strings modelling filesystem paths, one could use many more objects as input, including but obviously not limited to `io.StringIO` or `tempfile.TemporaryFile`.

**Comment by youngpm** [comment] 2017-01-13 15:58
@timtroendle Does the `BytesCollection` help you here? You pass it in bytes, and it maps it to GDAL's VSI's filesystem so that fiona can open it:

https://github.com/Toblerity/Fiona/blob/2c8f049c861654003c0a2929e46501bae7d6b4ad/fiona/collection.py#L425-L427

**Comment by sgillies** [comment] 2017-01-15 20:24
What @youngpm points out is correct: this feature exists in Fiona, albeit at a lower level, and I've come up with something in Rasterio – [in-memory files](https://mapbox.github.io/rasterio/topics/memory-files.html) – that I'd like to port to Fiona. Because `BytesCollection` and `MemoryFile` are lower level abtractions, they're not inconsistent with `fiona.open()` accepting file-like objects, and the feature you've suggested here would necessarily flow through the existing classes.

**Comment by timtroendle** [comment] 2017-01-16 10:26
Thanks a lot @youngpm and @sgillies for pointing this out. I had a quick look at `BytesCollection` before but got the wrong impression that it was not what I was looking for. Got it to work now!

It still would ease usability to handle that transparently in the `open` function; plus one would have access to the parameters in `open` which by using `BytesCollection` one does not.

**Comment by prcastro** [comment] 2017-09-06 17:31
This is essential when trying to open files from Hadoop File System. When using [HDFS3](https://github.com/dask/hdfs3), we can access a file from e.g. Pandas using a file-like object and passing it to `pandas.read`.

Implementing this here would also enable accessing the HDFS files from geopandas.

**Comment by sid-kap** [comment] 2018-05-09 03:37
Thanks! So it seems like `fiona.open` currently accepts `str` as an argument, and interprets that as URI. However, we also want to accept `str` types that include an entire file's contents (if I'm understanding the issue correctly). How would we figure out whether the argument is a URI or an actual file? (One option is to guess based on whether the starts with a `protocol://` or based on the string length, but that might be brittle. Another option is to take another boolean parameter that says whether it's a URI or file contents?)

**Comment by sgillies** [comment] 2018-05-09 03:44
@sid-kap I don't feel that taking a file's contents as a string as the OGR GeoJSON driver does is a good idea for Python, it's better to wrap the contents up with BytesIO and pass that object:

```
with fiona.open(BytesIO(content), ...) as collection:
    # read features
```

**Comment by sid-kap** [comment] 2018-05-09 03:51
Oh, right, that makes more sense. I suppose in Python 3 we could support either `BytesIO` or `bytes` if we wanted to make it more convenient (not sure if this is a good idea), but in Python 2 we should definitely take only `BytesIO`, since the binary type in Python 2 is just `str` which is ambiguous.

**Comment by sid-kap** [comment] 2018-05-09 03:56
I guess I'm a little confused about what the issue is about. It appears to me that `open` already works with anything that has a `read` method. And `BytesIO` follows the file interface, so it has a `read` method (I think).

**Comment by timtroendle** [comment] 2018-05-14 08:17
@sid-kap, thumbs up for working on this! Two examples of what I would like to do are given below. Using Fiona 1.7.11 (and Python 3.6), this throws an `AttributeError: '_io.BytesIO' object has no attribute 'split'`.

```Python
import fiona
import io
with open("my_file.geojson", "br") as f_bytes:
    file_buffered = io.BytesIO(f_bytes.read())
file_as_geojson = fiona.open(file_buffered)
```

```Python
import fiona
import tempfile

tmp = tempfile.NamedTemporaryFile()

with fiona.open('my_file.geojson') as source:
    source_driver = source.driver
    source_crs = source.crs
    source_schema = source.schema
    
with fiona.open(tmp, 'w', driver=source_driver, crs=source_crs, schema=source_schema) as c:
    c.write(rec)
```

**Comment by sid-kap** [comment] 2018-05-14 22:07
@timtroendle I tried your first example on a small file, and it seems to be working. Does this error only happen on large files?

**Comment by timtroendle** [comment] 2018-05-15 07:44
I had a quick look at the code and found that the master version of `fiona.open` already supports file-like objects; in contrast to the version on the maint-1.7 branch, where the latest release stems from (and which I used for my tests above). So maybe this issue is already resolved?

I had another look at the corresponding commit, it's 620bc475e09257bb1d947228f44e68628f8ae62e. In there, my `BytesIO` example from above has been added as a test case already.

@sgillies, you can see we are confused. ;-) Can you tell what's still missing here?

**Comment by sgillies** [comment] 2018-05-15 14:39
@timtroendle I apologize for leading you astray! I was rushing through tickets the other day and misread your comment. The only feature that Fiona is missing is support for pathlib objects: https://github.com/mapbox/rasterio/blob/master/rasterio/__init__.py#L202.

**Comment by bnaul** [comment] 2018-06-05 17:55
Should this be closed now that #587 is merged? Also, any idea when this will be released? It would be great to use this functionality for geopandas/geopandas#388.

**Comment by snorfalorpagus** [comment] 2018-06-05 18:06
Yes, I think everything discussed in this ticket has been implemented. We support `BytesIO` objects and also `pathlib.Path` objects in `fiona.open`.

Re: release, it will be part of 1.8. See https://github.com/Toblerity/Fiona/issues/396

**Closed** 2018-06-05 18:06 UTC
Labels: enhancement

**Comment by bnaul** [comment] 2018-06-05 23:00
Great! If a `1.8a2` wheel is posted soon w/ the relevant changes, that would be enough for me to get started on the geopandas work; would prefer to avoid configuring a Fiona source install if I can help it.
