### ISSUE TITLE
Fiona fails on reading shapefile (specific example)

### ISSUE THREAD

**Issue by ResidentMario** [Toblerity/Fiona#384] opened 2016-10-02 02:49 UTC
Hello,

The following short bit of code is sufficient to cause `fiona` to fail with a `KeyError`:

``` python
import fiona
import io
import zipfile
import requests

r = requests.get("https://www.dot.ny.gov/divisions/engineering/applications/traffic-data-viewer/traffic-data-viewer-repository/TDV_Shapefile_AADT_2014.zip", 
                 verify=False)
zipfile.ZipFile(io.BytesIO(r.content), 'r').extractall()
for feature in fiona.open("AADT_2014.shp"):
    print(feature)
```

This file opened without issue in QGIS.

**Comment by micahcochran** [comment] 2016-10-02 04:18
For the moment, I can't even get the file to download, period.  Using requests (Python 3.4) it gave a ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')).  So, I tried curl and wget, those pieces of software couldn't get an SSL connection.

If downloading a file is a part of causing your problem,  your code needs to be more robust.  That isn't Fiona fault.

I couldn't replicate the problem.

Does fiona.open line work with the already downloaded and extracted file?

**Comment by ResidentMario** [comment] 2016-10-02 04:25
Yes, this failure occurs with a local copy of the data; the requests piping is just an abstraction to get this error to a minimum reproducible example.

I think those pieces of software *can* get an SSL connection. The state website appears to have broken their SSL cert, and `wget` and `curl` sensibly reject a bad certificate by default&mdash;though I'm sure there's an option to allow them to just ignore SSL somewhere. `requests` should be able to skip past that problem when passed `verify=False`, as here. I don't know specifically what your error is, but I am using `python==3.5`, so maybe use that?

Anyway, besides the point. To reproduce you can download the data with an ordinary web browser and unzip it locally, then omit the `requests` and `zipfile` munging.

**Comment by mlaloux** [comment] 2016-10-02 11:17
look at my answer in  [Fiona throws KeyError when attempting to read a shapefile](http://gis.stackexchange.com/a/212758/2581)

**Comment by ResidentMario** [comment] 2016-10-02 18:03
That was indeed the issue, and the correct fix. Thank you.

I'm not sure whether or not runnings repairs like `GRASS` does is out-of-spec for `fiona`. I'm inclined to say that it is; if it is then this issue should be closed.

**Comment by sgillies** [comment] 2016-10-03 09:13
@ResidentMario @mlaloux I've downloaded that shapefile and cannot reproduce the problem using Fiona 1.7.0. I'm able to print every feature, many of which have no geometry, without exception.

3 years I fixed a related bug: https://github.com/Toblerity/Fiona/issues/31. It is possible that we had a regression in the meanwhile. Can you tell me what Fiona and GDAL versions you are using?

**Comment by mlaloux** [comment] 2016-10-03 15:33
Fiona  1.7.0.post2 and GDAL 1.11.3  on Mac OS X

**Comment by ResidentMario** [comment] 2016-10-03 15:35
I am using Fiona version `1.7.0.post2` (via `pip install fiona`) and GDAL version 1.11.3 (via `brew install gdal`).

**Comment by sgillies** [comment] 2016-11-15 15:33
@ResidentMario I figured this out. With GDAL >= 2.1, the "AADT_2014.shp" file has the geometry type `wkbLineStringM = 2002`, which Fiona 1.7.0 doesn't support. Fix for this bug is coming up right away in 1.7.1.

**Closed** 2016-11-16 15:53 UTC
Labels: bug
