### ISSUE TITLE
Fiona sdist has incorrect metadata and fails to pip install on arm64

### ISSUE THREAD

**Issue by psarka** [Toblerity/Fiona#1250] opened 2023-04-14 13:00 UTC
When pip installing Fiona on ec2 arm instance, it is built from source and fails because of incorrect metadata:

```
root@3ade2bb28223:/# pip install fiona==1.9.2
Collecting fiona==1.9.2
  Downloading Fiona-1.9.2.tar.gz (919 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 919.3/919.3 KB 10.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Requested fiona==1.9.2 from https://files.pythonhosted.org/packages/f1/57/61443cf8b58022cb117c26d8a25c8a1435b24de9dac5d7f848b94a2c584a/Fiona-1.9.2.tar.gz#sha256=f9263c5f97206bf2eb2c010d52e8ffc54e96886b0e698badde25ff109b32952a, but installing version 0.0.0
Discarding https://files.pythonhosted.org/packages/f1/57/61443cf8b58022cb117c26d8a25c8a1435b24de9dac5d7f848b94a2c584a/Fiona-1.9.2.tar.gz#sha256=f9263c5f97206bf2eb2c010d52e8ffc54e96886b0e698badde25ff109b32952a (from https://pypi.org/simple/fiona/) (requires-python:>=3.7): Requested fiona==1.9.2 from https://files.pythonhosted.org/packages/f1/57/61443cf8b58022cb117c26d8a25c8a1435b24de9dac5d7f848b94a2c584a/Fiona-1.9.2.tar.gz#sha256=f9263c5f97206bf2eb2c010d52e8ffc54e96886b0e698badde25ff109b32952a has inconsistent version: filename has '1.9.2', but metadata has '0.0.0'
ERROR: Could not find a version that satisfies the requirement fiona==1.9.2 (from versions: 0.5, 0.6, 0.6.1, 0.6.2, 0.7, 0.8, 0.9, 0.9.1, 0.10, 0.12, 0.12.1, 0.13, 0.14, 0.15, 0.16, 0.16.1, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.3.post1, 1.6.4, 1.7.0, 1.7.0.post2, 1.7.1, 1.7.1.post1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.9.post1, 1.7.10, 1.7.10.post1, 1.7.11, 1.7.11.post1, 1.7.11.post2, 1.7.12, 1.7.13, 1.8b1, 1.8b2, 1.8rc1, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.9.post1, 1.8.9.post2, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.13.post1, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.8.20, 1.8.21, 1.8.22, 1.9a1, 1.9a2, 1.9a3, 1.9b1, 1.9b2, 1.9.0, 1.9.1, 1.9.2, 1.9.3)
ERROR: No matching distribution found for fiona==1.9.2
```

I'm not sure exactly what is wrong, but I see lines like "preparing metadata (pyproject.toml)" and I also see no version in your pyproject.toml. So maybe that...

## Steps to reproduce the problem.
launch arm64 instance on ec2
install docker (or gdal, I suppose, but this repro is with docker)

```
docker run --rm -it osgeo/gdal:ubuntu-full-3.6.3 bash
apt-get update && apt-get install --yes python3-pip
pip install fiona==1.9.2
```

## Operating system

Amazon linux in my case, but it should not matter.

**Comment by sgillies** [comment] 2023-04-14 14:53
@psarka I can reproduce this. The good news is that any pip>=22.3 will build the project successfully. I don't yet understand why we require such a new pip. I'll update the documentation.

**Comment by mwtoews** [comment] 2023-04-17 01:10
This must be arm64-specific, as I can't reproduce this with pip 22.0.2 via x86-64. Looking at the sdist file, PKG-INFO has "Version: 1.9.2", so there are no obvious errors.

**Comment by HansBrende** [comment] 2023-08-30 19:02
I get the same thing with conda... last installable release appears to be 1.8.22. 

With literally nothing in my environment except python 3.9 and fiona 1.9.4:
```
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

With python 3.9 and fiona 1.8.22, everything works fine.

**Comment by sgillies** [comment] 2023-11-08 23:16
Closing this. We've documented that building from source requires pip >= 22.3.

**Closed by sgillies** 2023-11-08 23:16 UTC
