### ISSUE TITLE
Unable to import fiona in AWS Lambda Function

### ISSUE THREAD

**Issue by beck3905** [Toblerity/Fiona#1078] opened 2022-03-08 04:24 UTC
## Expected behavior and actual behavior.

I have an AWS Lambda Function that uses a Lambda Layer that contains fiona.  It has worked consistently for over a year now.  Today I updated from 1.8.20 to 1.8.21 and now my Lambda function raises an ImportError when it starts up.

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'fiona.ogrext'
```

I expected the Lambda to continue working after the update to 1.8.21.

I also attempted to include fiona in the Lambda package without the use of a Lambda Layer and received a different message:

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'app': libexpat.so.1: cannot open shared object file: No such file or directory
```

## Steps to reproduce the problem.

I use the SAM framework to build and deploy my Lambda functions.
1. Create a new SAM project using `sam init` and choose the Hello World template
2. Add fiona to the requirements.txt file provided by the template
3. Use the SAM CLI to build: `sam build`
4. Use the SAM CLI to deploy: `sam deploy --guided`
5. Once the stack has been created, open the AWS Lambda Console in web browser and open the Lambda function created by the SAM application
6. Test the Lambda function using the Lambda console

## Operating system

AWS Lambda
python3.9 runtime

AWS Lambda runs in a Linux-like environment but I am not sure of distro or version.  I was also able to produce this behavior on Mac OS X 12.2.1

## Fiona and GDAL version and provenance

The SAM framework installs the latest fiona version during the `sam build` command.  This also installs the binaries the fiona requires.  They are packed in the site-packages/Fiona.libs folder of the Lambda package.

Here are the contents of Fiona.libs:

```
libcurl-5ae56dbf.so.4.7.0
libgdal-e127aa65.so.30.0.1
libgeos-3097a6d2.so.3.10.2
libgeos_c-a8310b50.so.1.16.0
libjpeg-82e9a1fb.so.9.3.0
libjson-c-b8129721.so.5.1.0
libnghttp2-e183d352.so.14.21.1
libpcre-9513aab5.so.1.2.0
libpng16-8ebcc106.so.16.35.0
libproj-4d96bf55.so.22.2.1
libsqlite3-83998bda.so.0.8.6
libtiff-104e144c.so.5.7.0
```

**Comment by rbuffat** [comment] 2022-03-08 07:13
It looks like `libexpat.so.1` is not included in the 1.8.21 wheels while it was included in the 1.8.20 wheels. 

When I unpack the `Fiona-1.8.21-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64` wheel  the output of `ldd libgdal-e127aa65.so.30.0.1` is:

```
        linux-vdso.so.1 (0x00007ffdb5753000)
        libjson-c-b8129721.so.5.1.0 => not found
        libgeos_c-a8310b50.so.1.16.0 => not found
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f4ac21c5000)
        libpng16-8ebcc106.so.16.35.0 => not found
        libproj-4d96bf55.so.22.2.1 => not found
        libsqlite3-83998bda.so.0.8.6 => not found
        libtiff-104e144c.so.5.7.0 => not found
        libjpeg-82e9a1fb.so.9.3.0 => not found
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f4ac21a9000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f4ac21a4000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f4ac219f000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f4ac2198000)
        libpcre-9513aab5.so.1.2.0 => not found
        libcurl-5ae56dbf.so.4.7.0 => not found
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f4ac1f72000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f4ac1e8a000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f4ac1c80000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f4ac3b61000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f4ac1c63000)
```

**Comment by sgillies** [comment] 2022-03-08 17:41
Interesting! According to https://github.com/pypa/auditwheel/pull/301, auditwheel expects libexpat to be on the system since manylinux 2010. Also see https://github.com/pypa/auditwheel/blob/main/CHANGELOG.md#4000b1.

It may be that the default Lambda runtime is only compatible with manylinux1. This would be compatible with the first reported error.

`[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'fiona.ogrext'`

Fiona 1.8.21 provides no manylinux1 wheels, so the SAM builder may have fetched a source distribution, which would have failed to compile for lack of GDAL, etc. This may explain the absence of a fiona.ogrext module, it's normally a compiled module.

Is it possible to choose a more modern base for your Lambda runtime?

**Comment by beck3905** [comment] 2022-03-08 17:51
> Is it possible to choose a more modern base for your Lambda runtime?

I'm not sure.  I'm just using the standard python3.9 runtime with the x86_64 architecture.  I don't know of a more modern runtime without using my own docker container inside the Lambda, which adds a lot more complexity for me.  I am playing around with performing the `pip install` to create my Lambda layer inside various docker containers to see if they get me the correct dependencies.

**Comment by beck3905** [comment] 2022-03-09 14:57
@sgillies I did some experimenting today.  I did a `pip install fiona` on the following docker images:
* amazon/aws-lambda-python:3.7
* amazon/aws-lambda-python:3.8
* amazon/aws-lambda-python:3.9

All 3 used the manylinux2014 wheel.  According to the docs, Lambda does support manylinux2014.  I found that the libexpat library was included in Fiona.libs when installed with python 3.7, but not for 3.8 and 3.9.  I was able to import fiona locally in all 3 docker containers.  However, when I built my Lambda layer package using the site packages from the aws-lambda-python:3.9 container, my Lambda function using the Python3.9 runtime failed due to an import error looking for libexpat.

**Comment by vincentsarago** [comment] 2022-05-05 13:07
@sgillies note, I think I've seen this with latest rasterio wheels too

**Comment by sgillies** [comment] 2022-05-05 14:58
> I found that the libexpat library was included in Fiona.libs when installed with python 3.7, but not for 3.8 and 3.9.

@beck3905 Confirmed. That's unusual! I'm going to transfer this issue to the fiona-wheels repo and will look into it when I get a chance.

**Comment by sgillies** [comment] 2022-05-05 14:59
Or rather make a new issue.

**Comment by sgillies** [comment] 2022-12-08 22:10
It seems to me that the presence of libexpat in the Python 3.7 Fiona wheels is a quirk and can't be relied upon. It may go away in future releases.

I'm going to close this one as a wontfix. Auditwheel is excluding libexpat for manylinux_2_17_x86_64.manylinux2014_x86_64 and newer wheels by design. That project would need to change.

**Closed by sgillies** 2022-12-08 22:10 UTC
Labels: wontfix
