### ISSUE TITLE
undefined symbol: sqlite3_column_table_name

### ISSUE THREAD

**Issue by smjepard** [Toblerity/Fiona#294] opened 2015-11-08 22:34 UTC
Installed fiona, but get this error, trying to import it

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vladimir/anaconda/lib/python2.7/site-packages/fiona/__init__.py", line 72, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/vladimir/anaconda/lib/python2.7/site-packages/fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /usr/lib/libgdal.so.1: undefined symbol: sqlite3_column_table_name

Installed it through pip

**Comment by sgillies** [comment] 2015-11-09 00:22
Duplicate of #294 and not a valid Fiona issue.

**Closed by sgillies** 2015-11-09 00:22 UTC
