### ISSUE TITLE
Problem with AWS credentials not found when using `GeoDataFrame.to_file(..., driver='geojson')`

### ISSUE THREAD

**Issue by gcaria** [Toblerity/Fiona#1084] opened 2022-03-25 16:46 UTC
I suspect this is closely related to #1055, but at least now the error message is much more useful. The setup we're using is what @LewisJarrod describes [here](https://github.com/Toblerity/Fiona/issues/1055#issuecomment-1074232348).

Also in this case the workaround provided by @rbuffat in this [comment](https://github.com/Toblerity/Fiona/issues/1055#issuecomment-1029732024)  works.

```python
In [1]: gdf.to_file("s3://path/to/file.geojson", driver='GeoJSON')

---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_create()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: Failed to create GeoJSON datasource: /vsis3/path/to/file.geojson: AWS_SECRET_ACCESS_KEY and AWS_NO_SIGN_REQUEST configuration options not defined, and /home/jovyan/.aws/credentials not filled

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
/tmp/ipykernel_2391/208093662.py in <module>
----> 1 gdf.to_file("s3://path/to/file.geojson", driver='GeoJSON')

/srv/conda/envs/notebook/lib/python3.9/site-packages/geopandas/geodataframe.py in to_file(self, filename, driver, schema, index, **kwargs)
   1112         from geopandas.io.file import _to_file
   1113 
-> 1114         _to_file(self, filename, driver, schema, index, **kwargs)
   1115 
   1116     def set_crs(self, crs=None, epsg=None, inplace=False, allow_override=False):

/srv/conda/envs/notebook/lib/python3.9/site-packages/geopandas/io/file.py in _to_file(df, filename, driver, schema, index, mode, crs, **kwargs)
    391         elif crs:
    392             crs_wkt = crs.to_wkt("WKT1_GDAL")
--> 393         with fiona.open(
    394             filename, mode=mode, driver=driver, crs_wkt=crs_wkt, schema=schema, **kwargs
    395         ) as colxn:

/srv/conda/envs/notebook/lib/python3.9/site-packages/fiona/env.py in wrapper(*args, **kwargs)
    406     def wrapper(*args, **kwargs):
    407         if local._env:
--> 408             return f(*args, **kwargs)
    409         else:
    410             if isinstance(args[0], str):

/srv/conda/envs/notebook/lib/python3.9/site-packages/fiona/__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    270             else:
    271                 this_schema = None
--> 272             c = Collection(path, mode, crs=crs, driver=driver, schema=this_schema,
    273                            encoding=encoding, layer=layer, enabled_drivers=enabled_drivers, crs_wkt=crs_wkt,
    274                            **kwargs)

/srv/conda/envs/notebook/lib/python3.9/site-packages/fiona/collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    163             elif self.mode in ('a', 'w'):
    164                 self.session = WritingSession()
--> 165                 self.session.start(self, **kwargs)
    166         except IOError:
    167             self.session = None

fiona/ogrext.pyx in fiona.ogrext.WritingSession.start()

fiona/ogrext.pyx in fiona.ogrext.WritingSession.start()

fiona/_shim.pyx in fiona._shim.gdal_create()

DriverError: Failed to create GeoJSON datasource: /vsis3/path/to/file.geojson: AWS_SECRET_ACCESS_KEY and AWS_NO_SIGN_REQUEST configuration options not defined, and /home/jovyan/.aws/credentials not filled
```

**Comment by sgillies** [comment] 2022-12-08 22:13
Since the workaround works, I'm going to close as a duplicate of #1055. Should be fixed in 1.9.

**Closed by sgillies** 2022-12-08 22:13 UTC
