### ISSUE TITLE
Pip installed version gives 0 for missing values instead of None

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Fiona#604] opened 2018-07-14 23:19 UTC
Summary: fiona with pip installed turns missing values into 0 when reading a shapefile, while the conda installed version correctly returns None

## Steps to reproduce the problem.

The following scripts opens a shapefile, and reads the values of a certain column (file from this branch: https://github.com/ozak/geopandas/tree/e9b3e03ed68c68aee6099e7abb79bd822f922b6d/geopandas/tests/data/overlay/nybb_qgis):

```
import fiona
print(fiona.__version__)

result = []

with fiona.drivers():

    with fiona.open("geopandas/geopandas/tests/data/overlay/nybb_qgis/qgis-union.shp") as source:

        # Process only the records intersecting a box.
        for f in source:
            result.append(f['properties']['BoroCode'])

print(result)
```

With pip installed fiona, I get:

```
1.7.12
[5, 5, 5, 5, 5, 4, 4, 4, 3, 3, 3, 3, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

with conda installed:

```
1.7.12
[5, 5, 5, 5, 5, 4, 4, 4, 3, 3, 3, 3, 1, 1, 1, 1, 2, 2, 2, 2, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None]
```

The None values are correct (eg in QGIS it also indicates it as missing values)

## Operating system

Linux (Ubuntu 16.04), Python 3.6

**Comment by jorisvandenbossche** [comment] 2018-07-14 23:20
Is there a way to check with fiona which GDAL version it is using? 
I simply did `pip install fiona` (does that include GDAL in the wheels on linux? or does that expect to find a system installed GDAL?)

**Comment by sgillies** [comment] 2018-07-15 05:12
@jorisvandenbossche `fio --gdal-version` at the command line will report the version of the GDAL library that is loaded.

`pip install fiona` will *propbably* get the manylinux1 wheel from PyPI unless your linux system is incompatible with manylinux1 (based on CentOS 5.

Here's the ultimate check that one of my wheels is in play:

```
python -c "import fiona; import os; print('.dylibs' in os.listdir(os.path.dirname(fiona.__file__)))"
```

**Comment by jorisvandenbossche** [comment] 2018-07-15 14:23
`fio --gdal-version` gives `GDAL, version 2.2.4` for both (and checked that `fio` points to the correct path for both).
Both also gives False for the check for `.dylibs`.

With the conda one:

```
>>> import fiona
>>> fiona.__file__
'/home/joris/miniconda3/envs/geopandas-test-conda/lib/python3.6/site-packages/fiona/__init__.py'
>>> import os 
>>> os.listdir(os.path.dirname(fiona.__file__))
['rfc3339.py', 'errors.py', 'crs.py', 'transform.py', '__init__.py', '_transform.cpython-36m-x86_64-linux-gnu.so', '__pycache__', '_err.cpython-36m-x86_64-linux-gnu.so', '_geometry.cpython-36m-x86_64-linux-gnu.so', 'collection.py', '_drivers.cpython-36m-x86_64-linux-gnu.so', '_crs.cpython-36m-x86_64-linux-gnu.so', 'compat.py', 'tool.py', 'fio', 'inspector.py', 'ogrext.cpython-36m-x86_64-linux-gnu.so', 'drvsupport.py'] 
```

With pip:
```
>>> import fiona
>>> fiona.__file__
'/home/joris/miniconda3/envs/geopandas-test-failure/lib/python3.6/site-packages/fiona/__init__.py'
>>> import os
>>> os.listdir(os.path.dirname(fiona.__file__))
['rfc3339.py', 'gdal_data', 'errors.py', 'crs.py', '.libs', 'transform.py', '__init__.py', 'proj_data', '_transform.cpython-36m-x86_64-linux-gnu.so', '__pycache__', '_err.cpython-36m-x86_64-linux-gnu.so', '_geometry.cpython-36m-x86_64-linux-gnu.so', 'collection.py', '_drivers.cpython-36m-x86_64-linux-gnu.so', '_crs.cpython-36m-x86_64-linux-gnu.so', 'compat.py', 'tool.py', 'fio', 'inspector.py', 'ogrext.cpython-36m-x86_64-linux-gnu.so', 'drvsupport.py']
``` 

But so for the pip one, it certainly installed the manylinux wheel from PyPI (checked the metadata of the installed packages, there is a WHEEL file):

```
Wheel-Version: 1.0
Generator: bdist_wheel (0.30.0)
Root-Is-Purelib: false
Tag: cp36-cp36m-manylinux1_x86_64
```

I also forgot to note that I investigated this because of some strange errors on Travis CI (that were caused by the None -> 0 change), and on Travis for geopandas we were using pip.

**Comment by snorfalorpagus** [comment] 2018-07-15 15:46
This sounds like a duplicate of #460. This has been fixed, but only in
Fiona 1.8. As such, Fiona 1.7 doesn't fully support GDAL 2.2.

**Comment by sgillies** [comment] 2018-07-15 15:48
@jorisvandenbossche I believe you're seeing the issue Even pointed out to us in https://github.com/Toblerity/Fiona/issues/460 and which we've fixed in 1.8a1. The work around for 1.7 is: avoid writing features with empty fields.

**Closed by sgillies** 2018-07-15 15:48 UTC

**Comment by jorisvandenbossche** [comment] 2018-07-15 16:11
> it's a bit strange that conda doesn't have the problem though if it is related to the gdal version, they both use the same

Ah, that's because they applied the patch to 1.7.x

**Comment by jorisvandenbossche** [comment] 2018-07-15 16:15
Is there a timeline for 1.8? 
(I am running late with my own release of geopandas, so not that I have much ground to say anything about that :-), but IMO this is a rather serious bug)

**Comment by sgillies** [comment] 2018-07-17 18:35
@jorisvandenbossche I've made a 1.7.13 release to deal with this. See #608.

**Comment by jorisvandenbossche** [comment] 2018-07-18 12:31
Thank you very much!
