### ISSUE TITLE
GDAL 2.0

### ISSUE THREAD

**Issue by hroncok** [Toblerity/Fiona#239] opened 2015-07-06 22:40 UTC
In Fedora, we are slowly moving towards GDAL 2.0 and Fiona's tests suite seems to fail a lot. Is this simply because GDAL 2.0 is not supported, or are we doing something wrong?

The build and test log can be found [here](https://copr-be.cloud.fedoraproject.org/results/volter/gdal-2.0/fedora-rawhide-x86_64/python-Fiona-1.5.1-2.fc23/build.log.gz) (search for `Executing(%check):`).

If GDAL 2.0 is currently not supported, is it at least planned? And if so, is there a schedule (+ maybe something I can help with)?

Thanks

**Comment by sgillies** [comment] 2015-07-07 15:29
@hroncok GDAL 2.0 has features that I'm looking forward to using, for sure, but neither Fiona nor Rasterio are currently developed with an eye to GDAL 2.0. I imagine that we'll introduce 2.x branches of these that require GDAL 2.x. Let's talk about scheduling this work later this summer. In the meanwhile, I very much appreciate any notes that you have. Summaries are especially useful!

**Comment by hroncok** [comment] 2015-07-07 15:59
I don't have any notes, just an observation. Most tests fail with

    IndexError: list index out of range

**Comment by snorfalorpagus** [comment] 2015-07-08 22:19
I would say this doesn't look too bad. Obviously a lot is broken, but it's not everything! I wonder if anyone has written a guide to porting to GDAL 2.0 already. If not, it wouldn't hurt for us to keep notes and share with others.
```
============================= test session starts ==============================
platform darwin -- Python 3.4.3 -- py-1.4.26 -- pytest-2.7.0
rootdir: /Users/snorf/Desktop/gdal2/Fiona, inifile: 
collected 517 items

tests/test_bounds.py ....
tests/test_bytescollection.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
tests/test_cli.py FFF.
tests/test_collection.py .............................FF..F.FF..F.....FFFFFF...........F.........
tests/test_crs.py ..........
tests/test_drivers.py .
tests/test_feature.py .......
tests/test_fio_bounds.py ...........
tests/test_fio_cat.py FF.FF......F
tests/test_fio_load.py .....
tests/test_geojson.py F.
tests/test_geometry.py .........................
tests/test_geopackage.py ss
tests/test_layer.py ..............FF..F.FF..F.....FFF...............FF..F.FF..F.....FFF..............FF..F.FF..F.....FFF..
tests/test_listing.py ....FF......
tests/test_multiconxn.py F......
tests/test_non_counting_layer.py ......
tests/test_props.py ...
tests/test_read_drivers.py ..
tests/test_revolvingdoor.py F
tests/test_rfc3339.py ...........
tests/test_schema.py .FF
tests/test_slice.py FFFFF.
tests/test_unicode.py ...
tests/test_vfs.py ..............FF..F.FF..F.....FFF..............FFF..F.FF..F.....FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

**Comment by snorfalorpagus** [comment] 2015-07-08 22:57
It seems most of the errors were being caused by the new 64-bit integer type:

https://github.com/snorfalorpagus/Fiona/tree/gdal2

From `FAILED (errors=94, failures=9)`, to: `FAILED (errors=2, failures=1)`

The remaing issues seem to be with encodings (see #153) and `OGR_DS_SyncToDisk`.

**Comment by snorfalorpagus** [comment] 2015-07-10 23:32
The issue with `OGR_DS_SyncToDisk` appears to be related to laundering of field names. The tests in `test_schema.py` trigger an issue because some of the field names are more than 10 characters (the limit for ESRI Shapefiles). I'm not sure why the old code doesn't work here. It seems to, until it comes to writing the data.

**Comment by hroncok** [comment] 2015-07-27 14:17
BTW  http://svn.osgeo.org/gdal/branches/2.0/gdal/MIGRATION_GUIDE.TXT

**Comment by sebastic** [comment] 2015-10-23 18:32
As mentioned by @johanvdw in https://github.com/Toblerity/Fiona/issues/259#issuecomment-149126324, Debian is also considering moving to GDAL 2.0.

The build failure of the [fiona package](https://tracker.debian.org/fiona) is tracked in [Debian Bug #802808](https://bugs.debian.org/802808), in which you can also find the [build log](https://bugs.debian.org/cgi-bin/bugreport.cgi?filename=fiona_1.6.2-1_gdal-2.0.log;att=1;msg=5;bug=802808).

**Comment by rbuffat** [comment] 2015-10-23 19:17
@sebastic  Support for gdal 2.x is worked on in this PR: https://github.com/Toblerity/Fiona/pull/275
The missing piece is to add support for platforms not supporting gdal-config in setup.py.

**Comment by sgillies** [comment] 2016-06-11 00:55
Update: 1.7b1 is on PyPI now. See https://github.com/Toblerity/Fiona/issues/289.

**Closed** 2016-06-14 18:30 UTC
Labels: enhancement, expert, GDAL/OGR, GDAL2
