### ISSUE TITLE
Pb Reading Shapefile

### ISSUE THREAD

**Issue by oliverjack38** [Toblerity/Fiona#330] opened 2016-04-02 16:58 UTC
I Have some problem reading shapefiles created in QGis. I am not sure whether it is a Fiona or a QGis problem....

When I do:

``import fiona
l ="poly3.shp"

with fiona.open(l) as src:
    for feature in src:
        print feature
``

I get:

`
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-24-236e481de75e> in <module>()
      1 with fiona.open(l) as src:
----> 2         for feature in src:
      3                 print(feature)
      4 

fiona/ogrext.pyx in fiona.ogrext.Iterator.__next__ (fiona/ogrext.c:19067)()

fiona/ogrext.pyx in fiona.ogrext.FeatureBuilder.build (fiona/ogrext.c:3357)()

IndexError: list index out of range

`

if I do

`
c = fiona.open(l)
c.next()["geometry"]
`

I get

`
/usr/lib/python2.7/site-packages/fiona/collection.pyc in __next__(self)
    316         if not self.iterator:
    317             iter(self)
--> 318         return next(self.iterator)
    319 
    320     next = __next__

fiona/ogrext.pyx in fiona.ogrext.Iterator.__next__ (fiona/ogrext.c:19067)()

fiona/ogrext.pyx in fiona.ogrext.FeatureBuilder.build (fiona/ogrext.c:3357)()

IndexError: list index out of range
`

From what I understand the issue comes from the schema which does not seem to be read or set properly...

**Comment by sgillies** [comment] 2016-04-03 03:07
@oliverjack38 can you put the shapefile (including all its sidecar files) online somewhere for me to check?

**Comment by sgillies** [comment] 2016-04-03 03:09
Duplicate of #331

**Closed by sgillies** 2016-04-03 03:09 UTC
