### ISSUE TITLE
Strange interaction with shapely

### ISSUE THREAD

**Issue by d5h** [Toblerity/Fiona#276] opened 2015-09-25 17:48 UTC
I found a case where if fiona is imported before shapely it introduces a bug in unary_union.  The bug doesn't occur for all input to unary_union, which is why `SHAPES` in the example below is a little bit complicated.  But really it just contains five discs created by buffering points.  Four of the discs overlap, and the fifth is disconnected from the rest.

```
from shapely.geometry import shape
from shapely.ops import unary_union

import fiona

SHAPES = [{'type': 'Polygon', 'coordinates': (((-118.56603869194113, 34.170610009599535), (-118.56608998216255, 34.169346687481756), (-118.56628999677778, 34.16809362695623), (-118.56663680306134, 34.166862895148455), (-118.56712705502511, 34.165666343633774), (-118.56775602587462, 34.164515494340414), (-118.56851765373784, 34.163421428645435), (-118.56940460021865, 34.16239468072921), (-118.57040832120383, 34.16144513621278), (-118.5715191492371, 34.1605819370508), (-118.57272638666292, 34.15981339359243), (-118.57401840864213, 34.15914690465288), (-118.57538277504689, 34.15858888636169), (-118.57680635016028, 34.15814471046862), (-118.57827542903156, 34.157818652698026), (-118.57977586927568, 34.157613851645436), (-118.58129322705545, 34.15753227860938), (-118.58281289594473, 34.15757471864699), (-118.58432024734437, 34.15774076303395), (-118.5858007711087, 34.158028813200964), (-118.5872402150377, 34.1584360961085), (-118.58862472190091, 34.158958690912826), (-118.58994096268299, 34.15959156666778), (-118.59117626477459, 34.16032863070154), (-118.59231873388201, 34.16116278720546), (-118.59335736848543, 34.162086005473775), (-118.594282165748, 34.16308939714088), (-118.59508421785678, 34.164163301676325), (-118.59575579786753, 34.16529737931807), (-118.59629043422471, 34.16648071055294), (-118.59668297323455, 34.167701901190135), (-118.59692962888435, 34.16894919201905), (-118.59702801952055, 34.170210571998275), (-118.59697719102454, 34.171473893887985), (-118.59677762625344, 34.1727269912137), (-118.59643124064552, 34.17395779543568), (-118.59594136402258, 34.17515445219578), (-118.59531270875497, 34.176305435521215), (-118.59455132458704, 34.177399658884184), (-118.59366454054987, 34.1784265820452), (-118.59266089451401, 34.17937631264868), (-118.59155005105556, 34.18023970158872), (-118.59034270842277, 34.18100843122313), (-118.58905049549786, 34.18167509558204), (-118.58768585974661, 34.18223327179465), (-118.58626194723674, 34.18267758204236), (-118.58479247588504, 34.183003745437624), (-118.58329160315925, 34.18320861932586), (-118.58177378951666, 34.18329022960946), (-118.58025365890197, 34.18324778979992), (-118.57874585765812, 34.18308170861276), (-118.57726491321809, 34.182793586031536), (-118.57582509394825, 34.182386197878564), (-118.57444027150314, 34.181863469042135), (-118.57312378702579, 34.18123043561918), (-118.5718883224906, 34.18049319634061), (-118.57074577843392, 34.17965885374964), (-118.56970715925573, 34.17873544570326), (-118.56878246720017, 34.17773186786013), (-118.56798060603714, 34.17665778790533), (-118.5673092953729, 34.1755235523422), (-118.56677499641218, 34.17434008675271), (-118.56638284988276, 34.17311879049084), (-118.56613662671455, 34.17187142682629), (-118.56603869194113, 34.170610009599535)),)}, {'type': 'Polygon', 'coordinates': (((-118.556748074693, 34.166739098873514), (-118.55679045844353, 34.16569796519329), (-118.55695540400782, 34.16466529784411), (-118.55724131847307, 34.16365104161455), (-118.55764544421625, 34.16266496363603), (-118.55816388561934, 34.16171655934749), (-118.55879164672713, 34.16081496108871), (-118.55952267947914, 34.159968850201345), (-118.56034994204708, 34.15918637348211), (-118.56126546671214, 34.158475064790544), (-118.56226043662637, 34.15784177256371), (-118.56332527071767, 34.15729259393312), (-118.56444971592104, 34.156832816075955), (-118.56562294584936, 34.15646686536239), (-118.56683366495612, 34.15619826478638), (-118.56807021719113, 34.15602960008773), (-118.56932069810713, 34.15596249488946), (-118.57057306934401, 34.15599759508875), (-118.57181527439366, 34.1561345626505), (-118.57303535453747, 34.15637207886285), (-118.57422156384665, 34.156707857023235), (-118.57536248214412, 34.15713866443343), (-118.57644712484608, 34.15766035349271), (-118.57746504863137, 34.158267901591195), (-118.57840645192456, 34.158955459421236), (-118.57926226922974, 34.159716407243685), (-118.58002425840778, 34.16054341856971), (-118.58068508005834, 34.16142853064776), (-118.58123836824178, 34.162363221079254), (-118.58167879185807, 34.16333848982803), (-118.58200210608923, 34.16434494583632), (-118.58220519340604, 34.16537289741532), (-118.58228609373849, 34.16641244554155), (-118.58224402351516, 34.1674535791626), (-118.58207938338037, 34.16848627159488), (-118.58179375450948, 34.16950057708592), (-118.58138988355026, 34.170486726611166), (-118.5808716563295, 34.1714352219822), (-118.5802440605716, 34.172336927359), (-118.57951313798264, 34.173183157283404), (-118.57868592615746, 34.1739657603842), (-118.57777039086484, 34.17467719794503), (-118.57677534936113, 34.17531061657652), (-118.57571038546958, 34.17585991428944), (-118.57458575724331, 34.17631979933038), (-118.57341229810297, 34.17668584121014), (-118.5722013124035, 34.176954513431276), (-118.57096446644015, 34.17712322750076), (-118.56971367594794, 34.17719035789822), (-118.56846099118385, 34.17715525775811), (-118.56721848070468, 34.177018265113226), (-118.56599811496652, 34.17678069963941), (-118.56481165087337, 34.17644484993229), (-118.56367051839354, 34.17601395143958), (-118.5625857103417, 34.1754921552623), (-118.5615676763934, 34.17488448812676), (-118.56062622235746, 34.174196803915166), (-118.55977041567985, 34.17343572722344), (-118.55900849809134, 34.172608589492775), (-118.55834780624106, 34.171723358332386), (-118.5577947010805, 34.170788560717135), (-118.55735450667625, 34.16981320080218), (-118.55703145903774, 34.16880667314873), (-118.55682866544932, 34.167778672198935), (-118.556748074693, 34.166739098873514)),)}, {'type': 'Polygon', 'coordinates': (((-118.55292469303606, 34.16595174308923), (-118.55295916977727, 34.16510577995623), (-118.55309323235386, 34.16426669922997), (-118.55332558676723, 34.16344258147685), (-118.55365399260366, 34.162641362932035), (-118.5540752847152, 34.1618707590871), (-118.55458540379456, 34.161138190411876), (-118.5551794355466, 34.160450710924636), (-118.55585165807585, 34.15981494029706), (-118.55659559703165, 34.159237000146796), (-118.55740408797806, 34.158722455128924), (-118.55826934538725, 34.15827625939244), (-118.5591830375922, 34.157902708915124), (-118.5601363669777, 34.15760540017441), (-118.56112015463934, 34.15738719555034), (-118.5621249286977, 34.15725019579263), (-118.56314101542051, 34.15719571981529), (-118.56415863227855, 34.15722429201286), (-118.56516798204404, 34.157335637219276), (-118.5661593470288, 34.157528683357945), (-118.56712318255944, 34.15780157175726), (-118.56805020879362, 34.15815167503266), (-118.56893149999696, 34.15857562236365), (-118.56975857042465, 34.15906933192344), (-118.57052345598339, 34.15962805015013), (-118.57121879088962, 34.160246397482624), (-118.57183787858762, 34.160918420122655), (-118.57237475624464, 34.161637647326074), (-118.57282425220241, 34.162397153673545), (-118.57318203583031, 34.16318962572254), (-118.57344465929839, 34.16400743240073), (-118.57360959086552, 34.16484269846398), (-118.57367523935878, 34.1656873803131), (-118.57364096960461, 34.166533343439994), (-118.57350710865877, 34.16737244075817), (-118.57327494277142, 34.16819659106358), (-118.57294670511119, 34.16899785687011), (-118.57252555436318, 34.16976852086996), (-118.57201554440215, 34.17050116028155), (-118.57142158532992, 34.171188718368285), (-118.57074939624886, 34.1718245724379), (-118.57000545022426, 34.17240259766617), (-118.5691969119637, 34.172917226128476), (-118.56833156881329, 34.17336350046911), (-118.56741775573501, 34.173737121689584), (-118.56646427498917, 34.174034490593854), (-118.56548031129688, 34.1742527424898), (-118.56447534330229, 34.17438977481108), (-118.56345905219061, 34.17444426739231), (-118.56244122834552, 34.17441569520084), (-118.56143167694923, 34.17430433340253), (-118.56044012343848, 34.174111254711555), (-118.55947611973161, 34.1738383190505), (-118.55854895213392, 34.1734881556202), (-118.55766755181223, 34.17306413755284), (-118.55684040870474, 34.17257034939357), (-118.55607548969785, 34.17201154772482), (-118.55538016186041, 34.17139311531434), (-118.55476112147657, 34.170721009229865), (-118.5542243295608, 34.17000170342229), (-118.55377495447634, 34.16924212633167), (-118.55341732220879, 34.16844959411913), (-118.55315487477137, 34.167631740169064), (-118.55299013714045, 34.16679644154223), (-118.55292469303606, 34.16595174308923)),)}, {'type': 'Polygon', 'coordinates': (((-118.5383766285409, 34.16328685135829), (-118.53839439290935, 34.16285279380427), (-118.53846325264217, 34.16242227371968), (-118.53858254381856, 34.161999437184946), (-118.53875111688508, 34.16158835622319), (-118.53896734775402, 34.161192989589296), (-118.53922915346882, 34.160817144651766), (-118.53953401228446, 34.16046444073445), (-118.53987898796927, 34.160138274270885), (-118.54026075809281, 34.15984178610613), (-118.54067564602765, 34.15957783126089), (-118.54111965635624, 34.15934895144853), (-118.54158851334198, 34.15915735060909), (-118.54207770209439, 34.159004873695594), (-118.54258251203242, 34.15889298891639), (-118.54309808222779, 34.15882277360431), (-118.54361944819274, 34.15879490384818), (-118.54414158966264, 34.15880964798647), (-118.54465947891401, 34.158866864025434), (-118.54516812915412, 34.158966001006554), (-118.54566264251724, 34.15910610431018), (-118.5461382572063, 34.15928582484431), (-118.54659039332712, 34.159503432030114), (-118.54701469697477, 34.15975683045964), (-118.54740708214815, 34.16004358006547), (-118.54776377008979, 34.16036091960839), (-118.54808132567258, 34.160705793257534), (-118.54835669048295, 34.161074880007256), (-118.54858721228189, 34.16146462564819), (-118.54877067056, 34.16187127698469), (-118.54890529793994, 34.16229091796987), (-118.54898979721897, 34.16271950741059), (-118.54902335388766, 34.16315291787937), (-118.54900564400224, 34.16358697545914), (-118.548936837334, 34.16401749993786), (-118.54881759576462, 34.16444034506627), (-118.54864906694111, 34.164851438490984), (-118.54843287325092, 34.16524682097818), (-118.5481710962219, 34.16562268455013), (-118.54786625649666, 34.165975409166826), (-118.54752128957327, 34.166301597599336), (-118.54713951754545, 34.16659810815831), (-118.5467246171138, 34.16686208496244), (-118.54628058417612, 34.16709098545451), (-118.5458116953379, 34.16728260489975), (-118.54532246671366, 34.16743509763016), (-118.5448176104167, 34.16754699482952), (-118.54430198915688, 34.1676172186877), (-118.54378056938427, 34.16764509278749), (-118.54325837343136, 34.167630348623454), (-118.54274043111538, 34.16757312819036), (-118.54223173126827, 34.16747398261558), (-118.54173717366216, 34.167333866848985), (-118.54126152179435, 34.16715413046156), (-118.54080935698772, 34.166936504641356), (-118.54038503424967, 34.16668308551242), (-118.53999264031489, 34.166396313937646), (-118.53963595427753, 34.16607895200051), (-118.53931841119156, 34.16573405639249), (-118.53904306899027, 34.16536494896305), (-118.5388125790438, 34.1649751847163), (-118.53862916063751, 34.1645685175629), (-118.53849457961653, 34.16414886415756), (-118.53841013140197, 34.163720266170735), (-118.5383766285409, 34.16328685135829)),)}, {'type': 'Polygon', 'coordinates': (((-118.55512253551908, 34.18182198302544), (-118.55524556272468, 34.1788012918499), (-118.5557242288037, 34.17580516621931), (-118.55655388691109, 34.172862457406886), (-118.55772651237582, 34.170001499324215), (-118.55923078131038, 34.16724983588158), (-118.56105218084917, 34.16463395605946), (-118.56317314990851, 34.16217903923013), (-118.56557324907469, 34.159908713165315), (-118.56822935795527, 34.15784482704149), (-118.57111589807339, 34.156007241607526), (-118.5742050791501, 34.15441363851319), (-118.57746716640486, 34.153079350611584), (-118.58087076631308, 34.152017214847724), (-118.58438312809227, 34.15123744912873), (-118.58797045804513, 34.15074755434257), (-118.5915982437741, 34.1505522424529), (-118.59523158519146, 34.150653391349586), (-118.59883552918987, 34.15105002688135), (-118.60237540480482, 34.1517383322387), (-118.60581715569705, 34.152711684597016), (-118.60912766680688, 34.15396071867107), (-118.6122750820857, 34.15547341657759), (-118.61522911028966, 34.15723522315307), (-118.61796131592914, 34.15922918563224), (-118.62044539260128, 34.161436116360896), (-118.62265741609387, 34.163834776997156), (-118.62457607483154, 34.166402082449636), (-118.62618287544431, 34.16911332261137), (-118.62746232146625, 34.17194239977657), (-118.62840206342045, 34.174862079475126), (-118.62899301881305, 34.1778442523286), (-118.62922946083975, 34.180860204421926), (-118.62910907490391, 34.183880893600616), (-118.62863298234868, 34.18687722904126), (-118.62780573112006, 34.18982035140776), (-118.62663525339421, 34.19268191089593), (-118.62513279052224, 34.19543434048382), (-118.6233127859638, 34.198051121748456), (-118.62119274719419, 34.20050704067567), (-118.61879307787648, 34.2027784309837), (-118.61613688188424, 34.204843402597824), (-118.61324974104178, 34.206682053054344), (-118.61015946871355, 34.2082766597753), (-118.60689584161621, 34.20961185133874), (-118.60349031244948, 34.2106747560724), (-118.59997570613629, 34.21145512651805), (-118.59638590263013, 34.211945438548355), (-118.59275550938594, 34.21214096416522), (-118.58911952669686, 34.21203981726533), (-118.58551300917297, 34.21164297192323), (-118.58197072667798, 34.21095425301133), (-118.57852682804632, 34.209980299246936), (-118.57521451087406, 34.20873049902701), (-118.57206570061582, 34.20721689967743), (-118.56911074212366, 34.205454091003666), (-118.56637810663757, 34.203459064281084), (-118.56389411707903, 34.2012510480622), (-118.56168269431245, 34.19885132240365), (-118.55976512682756, 34.19628301332501), (-118.55815986605799, 34.193570869502025), (-118.55688234929433, 34.19074102336764), (-118.55594485187322, 34.18782073894299), (-118.55535637003244, 34.18483814884576), (-118.55512253551908, 34.18182198302544)),)}]

union = unary_union([shape(s) for s in SHAPES])
print union.type, len(union.geoms)

```

When run on my machine, this prints
```
MultiPolygon 2
```

If I simply move the `import fiona` line above the other two imports, and run again, I get
```
GeometryCollection 0
```

**Comment by sgillies** [comment] 2015-09-25 17:56
@d5h can you provide more information? Operating system, source of Fiona and Shapely distributions, etc.

**Comment by d5h** [comment] 2015-09-25 18:01
Yes, should have included that:
```
Darwin Kernel Version 14.3.0: Mon Mar 23 20:23:44 PDT 2015; root:xnu-2782.20.48~8/RELEASE_X86_64 x86_64
```
Fiona and Shapely were installed via pip
```
fiona==1.6.1
shapely==1.5.12
```
Here are my versions of other things
```
Python 2.7.6
GEOS 3.4.2-4
GDAL/OGR 1.11.2-2
```

**Comment by d5h** [comment] 2015-09-25 18:05
BTW, I noticed that you recently released Fiona 1.6.2, so I updated, but the issue remains.

**Comment by sgillies** [comment] 2015-10-01 21:27
Confirmed.

```
$ python shapely_first.py
('MultiPolygon', 2)
$ python fiona_first.py
('GeometryCollection', 0)
```

Good news is that it's not a problem on Linux.

```
$ uname
Linux
$ python shapely_first.py
MultiPolygon 2
$ python fiona_first.py
MultiPolygon 2
```

I guess I've screwed up the binary wheel builds on OS X.

**Comment by sgillies** [comment] 2015-10-01 22:20
The problem is not specifically with the wheels. It's due to something in my build environment.

```
$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

Importing Shapely after Fiona causes the GEOS shared library to be loaded twice. And apparently when ctypes is the second loader on OS X and the shared library is built using the version of clang above, there's a problem. Enabling DEBUG again (and C asserts), I get the following

```
$ uname
Darwin
$ python fiona_first.py
Assertion failed: (!"should never be reached"), function itemsTree, file AbstractSTRtree.cpp, line 371.
Abort trap: 6
```

instead of an empty GeometryCollection.

**Comment by sgillies** [comment] 2015-10-07 16:02
This is a Shapely issue. And there doesn't seem to be a work-around at the moment except to make sure that your GEOS library was compiled with `-DNDEBUG` so that you just get a (wrong) empty geometry collection instead of an assertion failure and program abort.

**Comment by sgillies** [comment] 2015-10-08 20:58
@d5h I've got a solution in https://github.com/Toblerity/Shapely/issues/327. Pending review it'll be in the 1.5.13 release.

Closing this issue.

**Closed by sgillies** 2015-10-08 20:58 UTC

**Comment by d5h** [comment] 2015-10-08 22:04
Thanks so much @sgillies!

**Comment by sgillies** [comment] 2018-01-01 22:14
See also https://github.com/Toblerity/Shapely/issues/553.
