### ISSUE TITLE
boto3 is a required dependency?

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Fiona#625] opened 2018-09-14 08:55 UTC
I am testing fiona master, and when simply opening a local file, I get:

```
Traceback (most recent call last):
  File "test_geopandas_memory.py", line 39, in <module>
    c = fiona.collection(path)
  File "/home/joris/scipy/repos/Fiona/fiona/__init__.py", line 249, in open
    enabled_drivers=enabled_drivers, **kwargs)
  File "/home/joris/scipy/repos/Fiona/fiona/collection.py", line 150, in __init__
    self.env = AWSGDALEnv()
  File "/home/joris/scipy/repos/Fiona/fiona/drvsupport.py", line 159, in __init__
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

It seems that `boto3` is regarded as an optional dependency (it is in the `extras_require` in setup.py), but then the above should work without having boto3? 

The import of `boto3` is done within the class definition of `AWSGDALEnv`, but then that class should not have been instantiated in my case? 
It is called from

https://github.com/Toblerity/Fiona/blob/cf4c6a51764f1de6f6a0fc38cf5cde89fa324a3e/fiona/collection.py#L146-L150

but that seems a bit strange anyway, as both if and else statement do the same.

---

Running fiona master with GDAL 2.3.1 installed from conda-forge, on Ubuntu 16.04, Python 3.5

**Comment by snorfalorpagus** [comment] 2018-09-14 10:16
Duplicate of #507.

**Closed by snorfalorpagus** 2018-09-14 10:16 UTC

**Comment by jorisvandenbossche** [comment] 2018-09-14 10:57
Whoops, sorry, should have looked for open issues first.
