### ISSUE TITLE
Error opening shapefile using Fiona

### ISSUE THREAD

**Issue by lokendrarathore** [Toblerity/Fiona#767] opened 2019-06-25 03:54 UTC
I am trying to read a shapefile using Fiona, but it shows `Invalid path error`. Following is the command I give:
`fiona.open('M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp')`

The above command displays the following error: 
`TypeError: invalid path: UnparsedPath(path='M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp')`

The traceback of the problem is: 
```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-250cf85560e8> in <module>()
----> 1 fiona.open('M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp')

c:\python27\lib\site-packages\fiona\fiona\env.pyc in wrapper(*args, **kwargs)
    404             with Env.from_defaults(session=session):
    405                 log.debug("Credentialized: {!r}".format(getenv()))
--> 406                 return f(*args, **kwargs)
    407     return wrapper
    408 

c:\python27\lib\site-packages\fiona\__init__.pyc in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    255         if mode in ('a', 'r'):
    256             c = Collection(path, mode, driver=driver, encoding=encoding,
--> 257                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
    258         elif mode == 'w':
    259             if schema:

c:\python27\lib\site-packages\fiona\fiona\collection.pyc in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
     54 
     55         if not isinstance(path, (string_types, Path)):
---> 56             raise TypeError("invalid path: %r" % path)
     57         if not isinstance(mode, string_types) or mode not in ('r', 'w', 'a'):
     58             raise TypeError("invalid mode: %r" % mode)

TypeError: invalid path: UnparsedPath(path='M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp')
```
I have installed fiona 1.8.6 and geopandas 0.5.0 version installed in my system. I am using python 2.7

**Comment by sgillies** [comment] 2019-06-25 15:54
Thanks for the report, I'm looking into it.

**Comment by sgillies** [comment] 2019-06-25 16:22
I can't reproduce the issue here with python 3.6:

```
>>> from fiona.path import Path, parse_path
>>> from fiona import string_types
>>> parse_path('M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp')
UnparsedPath(path='M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp')
>>> path = parse_path('M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp')
>>> isinstance(path, (string_types, Path))
True
```

Which specific python 2 version are you using? 

I'd love to see what `Path` resolves to at line 55 just before the exception. Any chance you could run your script with the Python debugger and inspect that?

**Comment by lokendrarathore** [comment] 2019-06-26 04:09
I am using python 2.7.15
The issue is still unresolved.  Running script with python debugger gives the same error: 
```
Exception AttributeError: "'Collection' object has no attribute 'session'" in <object repr() failed> ignored
*** TypeError: invalid path: UnparsedPath(path='M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp')
```

**Comment by sgillies** [comment] 2019-06-26 04:26
@lokendrarathore I mean running it with the debugger like shown at https://stackoverflow.com/a/2438834/159235. This will give you a pdb prompt and if you type `repr(Path)` we can see what the Path object is.

**Comment by lokendrarathore** [comment] 2019-06-26 05:32
`repr(Path)` gives `<class 'fiona.pat.Path'>`

**Comment by sgillies** [comment] 2019-06-27 13:49
I'm sorry about this. I can't reproduce the problem with python 3.6 and while I don't have a windows computer to test on, the code involved isn't operating system specific. This project is going to quit supporting python 2.7 very soon (as will the rest of the scientific python ecosystem), so I'm going to mark this one as "wontfix".

**Closed by sgillies** 2019-06-27 13:49 UTC
