### ISSUE TITLE
Geometry saved as MultiPolygon is loaded as Polygon and order changes

### ISSUE THREAD

**Issue by lordi** [Toblerity/Fiona#868] opened 2020-03-23 09:17 UTC
## Expected behavior and actual behavior.

I save a 3D multipolygon shapefile with row geometry type "MultiPolygon". When I read this file again I expect that the row geometry type is still "MultiPolygon". But actually it is downgraded to "Polygon" and also the polygons order in this geometry is changed.

This only happens for certain coordinates (see Run 2 below -- only the coordinates changed!).

## Steps to reproduce the problem.

```
import fiona
from pprint import pprint

fn = '/tmp/test_mp.shp'
opts = {
    'driver': 'ESRI Shapefile',
    'schema': {'geometry': '3D MultiPolygon', 'properties': {}}
}

# Run 1 - OK
polygons = [
    [[[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, 0.0]]],
    [[[0.0, 0.0, 0.0], [2.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, 0.0]]]
]

with fiona.open(fn, mode='w', **opts) as c:
    c.write({'geometry': {'type': 'MultiPolygon', 'coordinates': polygons}, 'properties': {}})

with fiona.open(fn, mode='r', **opts) as c:
    feature = next(iter(c))
    pprint(feature['geometry'])
    assert feature['geometry']['type'] == 'MultiPolygon' # ok!

# Run 2 - Failing
polygons = [
        [[[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, 0.0]]],
        [[[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 0.0]]],
    ]

with fiona.open(fn, mode='w', **opts) as c:
    c.write({'geometry': {'type': 'MultiPolygon', 'coordinates': polygons}, 'properties': {}})

with fiona.open(fn, mode='r', **opts) as c:
    feature = next(iter(c))
    pprint(feature['geometry'])
    assert feature['geometry']['type'] == 'MultiPolygon'
    # type is downgraded to 'Polygon' here and polygon order is changed
```

## Operating system

Arch Linux

## Fiona and GDAL version and provenance

 * Python 3.8
 * Fiona==1.8.13.post1 installed from PyPI using pip 20.0.2
 * GDAL 3.0.4, released 2020/01/28

**Comment by rbuffat** [comment] 2020-03-23 09:27
With the GeoJSON driver it seems to give the correct result.

```
opts = {
    'driver': 'GeoJSON',
    'schema': {'geometry': '3D MultiPolygon', 'properties': {}}
}
```

**Comment by lordi** [comment] 2020-03-23 09:36
Yea, it is probably a OGR/GDAL issue then?

**Comment by rbuffat** [comment] 2020-03-23 11:25
I suspect the issue is that the "bad" MultiPolyong is not valid according to the ogc simple feature specification. 

See: https://github.com/OSGeo/gdal/issues/1787

```
ogrinfo -al -q -sql "select st_isvalid(geom) from test_mp" test_mp.gpkg 
GEOS warning: Too few points in geometry component at or near point 0 0 0

Layer name: SELECT
OGRFeature(SELECT):0
  st_isvalid(geom) (Integer) = 0

```

**Comment by lordi** [comment] 2020-03-23 16:43
Ok, thanks for the pointers so far. I don't see why it is bad tho, and why bad should be a reason to mingle it because shapefile *in principle* should also work for invalid geometries.

But I guess this issue is one or more layers down, and not really a thing that fiona is concerned with.

**Comment by rbuffat** [comment] 2020-03-23 20:18
I'm not familiar with the Shapefile format, respectively the implementation of the gdal driver.  But after reading https://github.com/OSGeo/gdal/issues/1787#issuecomment-522250212 I suspect it is best to check the validity of the geometry before writing them E.g. by using the shapely library.  GeoJSON and GPKG seem to be more tolerant with writing invalid geometries.

It's not ideal that the Shapefile driver does not raise an error when it can't handle invalid geometries and does something unexpected. But this is probably something that should be handled withing gdal and not fiona.

**Comment by lordi** [comment] 2020-03-24 08:18
Thanks for taking the effort and escalating the issue to gdal.

**Comment by sgillies** [comment] 2020-03-24 15:01
@lordi thanks for reporting this! I wasn't aware of the issue before.

@rbuffat thanks for reporting upstream!

**Comment by sgillies** [comment] 2020-03-25 17:44
I will close this one. In #870 I propose a documentation fix.

**Closed by sgillies** 2020-03-25 17:44 UTC
Labels: upstream
