### ISSUE TITLE
bug:  module 'fiona' has no attribute 'path'

### ISSUE THREAD

**Issue by peterdudfield** [Toblerity/Fiona#1440] opened 2024-09-04 09:02 UTC
## Expected behavior and actual behavior.
Load a geopandas file, but got error. 

## Steps to reproduce the problem.

Loading a file with geopandas==0.14.2

![Screenshot 2024-09-04 at 09 59 27](https://github.com/user-attachments/assets/7b37d923-b890-429f-8ab7-03aff79d73bb)

https://github.com/openclimatefix/analysis-dashboard/actions/runs/10698298217

But perhaps this is sovled with new geopandas version?

## Operating system

Linux

## Fiona and GDAL version and provenance

1.10.0
This didnt happen with 1.9.6

**Comment by soxofaan** [comment] 2024-09-04 09:43
Same issue over here.

stack trace to give more info
```
.../datacube.py:402: in from_fiona
    gdf = gpd.read_file(paths[0], driver=driver)
.../site-packages/geopandas/io/file.py:281: in _read_file
    return _read_file_fiona(
.../site-packages/geopandas/io/file.py:299: in _read_file_fiona
    if _is_zip(str(path_or_bytes)):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    def _is_zip(path):
        """Check if a given path is a zipfile"""
>       parsed = fiona.path.ParsedPath.from_uri(path)
E       AttributeError: module 'fiona' has no attribute 'path'
```

Environment:  python 3.8, geopandas-0.13.2, fiona-1.10.0

**Comment by jorisvandenbossche** [comment] 2024-09-04 10:00
This has already been fixed in geopandas (I think in gepandas >= 0.14.4) so if you want to use the latest fiona, you also have to use the latest geopandas (or if you want to use an older geopandas, you will also have to pin fiona to an older release).

**Comment by soxofaan** [comment] 2024-09-04 10:10
Thanks for that quick update
Unfortunately we're on python3.8 at the moment, which ties us to geopandas<0.14.0,  so we'll have to pin down fiona at the moment

**Comment by sgillies** [comment] 2024-09-04 18:13
@peterdudfield I'm looking into it. The path module is deprecated and will be removed in the future, but it's still there in 1.10.0. The problem is that `fiona/__init__.py` imports functions from `fiona._path` now and not `fiona.path`, so `fiona.path` is no longer in our namespace.

```
>>> import fiona
>>> fiona.path
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: module 'fiona' has no attribute 'path'
>>> fiona._path
<module 'fiona._path' from '/Users/seangillies/.local/pipx/venvs/fiona/lib/python3.11/site-packages/fiona/_path.py'>
```

Do pin to 1.9.6. Geopandas only uses fiona to read and write data and there aren't big improvements there in 1.10.0.

**Closed by sgillies** 2024-09-04 18:13 UTC
Labels: deprecation
