### ISSUE TITLE
fiona.errors.SchemaError: cannot convert to GBK

### ISSUE THREAD

**Issue by CUG499251662** [Toblerity/Fiona#863] opened 2020-02-24 04:34 UTC
The following error happens whatever encoding set I use, GBK,UTF8,GB2312 etc . Is it an error due to GDAL ?
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "F:/WorkSpace/PyScriptTest/src/test.py", line 66, in <module>
    gdf.to_file('gdfrSS',driver='ESRI Shapefile')
  File "D:\ProgramData\Anaconda3\envs\gdal2\lib\site-packages\geopandas\geodataframe.py", line 504, in to_file
    to_file(self, filename, driver, schema, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\gdal2\lib\site-packages\geopandas\io\file.py", line 128, in to_file
    filename, "w", driver=driver, crs=df.crs, schema=schema, **kwargs
  File "D:\ProgramData\Anaconda3\envs\gdal2\lib\site-packages\fiona\env.py", line 396, in wrapper
    return f(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\gdal2\lib\site-packages\fiona\__init__.py", line 263, in open
    **kwargs)
  File "D:\ProgramData\Anaconda3\envs\gdal2\lib\site-packages\fiona\collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 1123, in fiona.ogrext.WritingSession.start
fiona.errors.SchemaError: Failed to create field name 'A_1': cannot convert to GBK

Process finished with exit code 1

**Comment by sgillies** [comment] 2020-02-24 16:08
@CUG499251662 that error arises from https://github.com/OSGeo/gdal/blob/3d7e5546f40bcefb6e0c56e1227aad2a4b4285ee/gdal/ogr/ogrsf_frmts/shape/ogrshapelayer.cpp#L1765-L1770 and tells me that your GDAL/OGR library build does not include the libiconv support that we expect. The problem is downstream from the Fiona and GeoPandas project and I am going to close this issue. If you installed geopandas and fiona using the conda-forge channel, you should report the problem at https://github.com/conda-forge/gdal-feedstock. If you installed geopandas and fiona using the default anaconda channel, you will have to report the issue to the anaconda project.

**Closed by sgillies** 2020-02-24 16:08 UTC
