### ISSUE TITLE
Cannot import fiona - fiona/path.py -> No module named 'attr'

### ISSUE THREAD

**Issue by darrenleeweber** [Toblerity/Fiona#640] opened 2018-10-09 23:37 UTC
Cannot import fiona - `/fiona/path.py` -> `No module named 'attr'`

```
$ uname -a
Linux aa1a8591d68c 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 GNU/Linux
```

```
$ python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/envs/jupiter-ingests/lib/python3.6/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/usr/local/envs/jupiter-ingests/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
  File "fiona/ogrext.pyx", line 35, in init fiona.ogrext
  File "/usr/local/envs/jupiter-ingests/lib/python3.6/site-packages/fiona/path.py", line 6, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

```
$ conda env export
name: test-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_1003
  - awscli=1.16.29=py36_0
  - blas=1.1=openblas
  - bokeh=0.13.0=py36_0
  - boost-cpp=1.67.0=h3a22d5f_0
  - boto3=1.9.19=py_0
  - botocore=1.12.19=py_0
  - bottleneck=1.2.1=py36h7eb728f_1
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.8.24=ha4d7672_0
  - cairo=1.14.12=he6fea26_5
  - certifi=2018.8.24=py36_1001
  - cffi=1.11.5=py36h5e8e0c9_1
  - cftime=1.0.1=py36h7eb728f_1
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - click-plugins=1.0.4=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=0.6.0=py_0
  - colorama=0.3.9=py_1
  - cryptography=2.3.1=py36hdffb7b8_0
  - cryptography-vectors=2.3.1=py36_1000
  - curl=7.61.1=h74213dd_2
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py36h470a237_1
  - dask=0.19.3=py_0
  - dask-core=0.19.3=py_0
  - dbus=1.13.0=h3a4f0e9_0
  - descartes=1.1.0=py_2
  - distributed=1.23.3=py36_1000
  - docutils=0.14=py36_1001
  - expat=2.2.5=hfc679d8_2
  - fiona=1.8a3=py36hb00a9d7_0
  - fontconfig=2.13.1=h65d0f4c_0
  - freetype=2.9.1=h6debe1e_4
  - freexl=1.0.5=h470a237_2
  - gdal=2.2.4=py36hb00a9d7_9
  - geopandas=0.4.0=py_1
  - geos=3.6.2=hfc679d8_3
  - geotiff=1.4.2=h700e5ad_4
  - gettext=0.19.8.1=h5e8e0c9_1
  - giflib=5.1.4=h470a237_1
  - glib=2.55.0=h464dc38_2
  - gst-plugins-base=1.12.5=hde13a9d_0
  - gstreamer=1.12.5=h61a6719_0
  - h5netcdf=0.6.2=py_0
  - h5py=2.8.0=py36h7eb728f_3
  - hdf4=4.2.13=h951d187_2
  - hdf5=1.10.2=hc401514_2
  - heapdict=1.0.0=py36_1000
  - icu=58.2=hfc679d8_0
  - idna=2.7=py36_1002
  - jinja2=2.10=py_1
  - jmespath=0.9.3=py_1
  - jpeg=9c=h470a237_1
  - json-c=0.12.1=h470a237_1
  - kealib=1.4.9=h0bee7d0_2
  - kiwisolver=1.0.1=py36h2d50403_2
  - krb5=1.16.1=hbb41f41_0
  - libcurl=7.61.1=hbdb9355_2
  - libdap4=3.19.1=h8fe5423_1
  - libedit=3.1.20170329=haf1bffa_1
  - libffi=3.2.1=hfc679d8_5
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgdal=2.2.4=hbd6f514_9
  - libgfortran=3.0.0=1
  - libiconv=1.15=h470a237_3
  - libkml=1.3.0=hccc92b1_8
  - libnetcdf=4.6.1=he6cff42_8
  - libpng=1.6.35=ha92aebf_2
  - libpq=10.5=he29860b_0
  - libspatialindex=1.8.5=hfc679d8_3
  - libspatialite=4.3.0a=hdfcc80b_23
  - libssh2=1.8.0=h5b517e9_2
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he6b73bb_2
  - libuuid=2.32.1=h470a237_2
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - locket=0.2.0=py_2
  - markupsafe=1.0=py36h470a237_1
  - matplotlib=3.0.0=2
  - matplotlib-base=3.0.0=py36hc039c98_2
  - msgpack-python=0.5.6=py36h2d50403_3
  - munch=2.3.2=py_0
  - ncurses=6.1=hfc679d8_1
  - netcdf4=1.4.1=py36h62672b6_0
  - numpy=1.15.2=py36_blas_openblashd3ea46f_1
  - openblas=0.2.20=8
  - openjpeg=2.3.0=h0e734dc_3
  - openssl=1.0.2p=h470a237_0
  - packaging=18.0=py_0
  - pandas=0.23.4=py36hf8a1672_0
  - partd=0.3.8=py_1
  - pcre=8.41=hfc679d8_3
  - pip=18.1=py36_1000
  - pixman=0.34.0=h470a237_3
  - poppler=0.67.0=h4d7e492_3
  - poppler-data=0.4.9=0
  - postgresql=10.5=h66035e0_0
  - proj4=4.9.3=h470a237_8
  - psutil=5.4.7=py36h470a237_1
  - psycopg2=2.7.5=py36hdffb7b8_2
  - pthread-stubs=0.4=h470a237_1
  - pyasn1=0.4.4=py_0
  - pycparser=2.19=py_0
  - pyopenssl=18.0.0=py36_1000
  - pyparsing=2.2.2=py_0
  - pyproj=1.9.5.1=py36h508ed2a_5
  - pyqt=5.6.0=py36h8210e8a_7
  - pysal=1.14.4.post2=py36_1
  - pysocks=1.6.8=py36_1002
  - python=3.6.6=h5001a0f_0
  - python-dateutil=2.7.3=py_0
  - pytz=2018.5=py_0
  - pyyaml=3.13=py36h470a237_1
  - qt=5.6.2=hf70d934_9
  - readline=7.0=haf1bffa_1
  - requests=2.19.1=py36_1
  - rsa=3.4.2=py_1
  - rtree=0.8.3=py36_1000
  - s3transfer=0.1.13=py36_1001
  - scipy=1.1.0=py36_blas_openblash7943236_201
  - setuptools=40.4.3=py36_0
  - shapely=1.6.4=py36h164cb2d_1
  - sip=4.18.1=py36hfc679d8_0
  - six=1.11.0=py36_1001
  - sortedcontainers=2.0.5=py_0
  - sqlalchemy=1.2.12=py36h470a237_0
  - sqlite=3.25.2=hb1c47c0_0
  - tblib=1.3.2=py_1
  - tk=8.6.8=ha92aebf_0
  - toolz=0.9.0=py_1
  - tornado=5.1.1=py36h470a237_0
  - urllib3=1.23=py36_1001
  - wheel=0.32.1=py36_0
  - xarray=0.10.9=py36_0
  - xerces-c=3.2.0=h5d6a6da_2
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.2=h8c8a85c_6
  - xorg-libx11=1.6.6=h470a237_0
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - xz=5.2.4=h470a237_1
  - yaml=0.1.7=h470a237_1
  - zict=0.1.3=py_0
  - zlib=1.2.11=h470a237_3
  - pip:
    - msgpack==0.5.6
```

**Comment by sgillies** [comment] 2018-10-10 19:09
Thanks for the report @darrenleeweber ! This is a duplicate of #638 and will be fixed in 1.8b1 (coming Monday).

**Closed by sgillies** 2018-10-10 19:09 UTC
