### ISSUE TITLE
Reading shapefile with NULL date fields breaks iteration

### ISSUE THREAD

**Issue by mhearne-usgs** [Toblerity/Fiona#454] opened 2017-06-08 22:49 UTC
[city_bounds.zip](https://github.com/Toblerity/Fiona/files/1062597/city_bounds.zip)
[fiona_test.zip](https://github.com/Toblerity/Fiona/files/1062605/fiona_test.zip)

## Please note

Fiona contains extension modules and is thus susceptible to C library compatibility issues. If you are reporting an installation or module import issue, please note that this project only accepts reports about problems with packages downloaded from the Python Package Index. Conda users should take issues to one of the following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/fiona-feedstock

## Expected behavior and actual behavior.

Using the attached script and data file (a shapefile from the city of L.A.), in fiona 1.7.7 I get the following error:

 File "fiona/ogrext.pyx", line 1187, in fiona.ogrext.Iterator.__next__ (fiona/ogrext2.c:20124)
  File "fiona/ogrext.pyx", line 210, in fiona.ogrext.FeatureBuilder.build (fiona/ogrext2.c:4387)
ValueError: year 0 is out of range

The error seems to have something to do with the "created_da" field (of 'date' type, I think) having NULL values.

I can read this file in QGIS and in fiona 1.7.6.  Is this a deliberate feature of fiona - in other words, do I have to edit my shapefile in some other tool to have non-NULL date fields?

I did see that there was a similar issue some time ago, that example had corrupted data.  I don't *believe* that my data is corrupted, but perhaps someone can correct me.

https://github.com/Toblerity/Fiona/issues/326

## Steps to reproduce the problem.

See attached zip file with script and data files.

## Operating system

OS: Mac OS 10.12.5 (16F73)
Python: Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:31:56) 

## Fiona version and provenance

Fiona: 1.7.7 through conda-forge

**Comment by sgillies** [comment] 2017-06-09 06:54
Hi @mhearne-usgs. Can you check and report the GDAL conda package version that accompanies Fiona? I haven't touched the code around date field handling in 1.7.7 and I'm aware of some changes around handling null and empty fields in GDAL 2.2.

**Comment by mhearne-usgs** [comment] 2017-06-09 13:53
@sgillies gdalinfo --version
GDAL 2.1.3, released 2017/20/01

Is that the version of the library, or just the tools?

**Comment by sgillies** [comment] 2017-06-09 14:03
@mhearne-usgs I checked the fiona recipe and found https://github.com/conda-forge/fiona-feedstock/blob/master/recipe/meta.yaml#L24. Can you confirm using the conda-installed gdalinfo program?

**Comment by snorfalorpagus** [comment] 2017-07-08 21:59
This sounds like the issue from #460.

**Comment by sgillies** [comment] 2017-07-28 04:57
Closing since #460 is closed.

**Closed by sgillies** 2017-07-28 04:57 UTC

**Comment by wiktorn** [comment] 2018-03-25 10:39
I have the same problem as reported here with Fiona 1.7.11 and GDAL 2.2.1 on Ubuntu. I downloaded the fiona_test.zip from this ticket and it's still reproducible:
```
w@ubuntu:~/Downloads/tf$ ~/venv-osm-borders/bin/pip install -U Fiona==1.7.6
Collecting Fiona==1.7.6
  Using cached Fiona-1.7.6-cp36-cp36m-manylinux1_x86_64.whl
Requirement already up-to-date: cligj in /home/w/venv-osm-borders/lib/python3.6/site-packages (from Fiona==1.7.6)
Requirement already up-to-date: six in /home/w/venv-osm-borders/lib/python3.6/site-packages (from Fiona==1.7.6)
Requirement already up-to-date: click-plugins in /home/w/venv-osm-borders/lib/python3.6/site-packages (from Fiona==1.7.6)
Requirement already up-to-date: munch in /home/w/venv-osm-borders/lib/python3.6/site-packages (from Fiona==1.7.6)
Requirement already up-to-date: click>=4.0 in /home/w/venv-osm-borders/lib/python3.6/site-packages (from cligj->Fiona==1.7.6)
Installing collected packages: Fiona
  Found existing installation: Fiona 1.7.11
    Uninstalling Fiona-1.7.11:
      Successfully uninstalled Fiona-1.7.11
Successfully installed Fiona-1.7.6
w@ubuntu:~/Downloads/tf$ ~/venv-osm-borders/bin/python testfiona.py 
w@ubuntu:~/Downloads/tf$ ~/venv-osm-borders/bin/pip install -U Fiona==1.7.7
Collecting Fiona==1.7.7
  Using cached Fiona-1.7.7-cp36-cp36m-manylinux1_x86_64.whl
Requirement already up-to-date: cligj in /home/w/venv-osm-borders/lib/python3.6/site-packages (from Fiona==1.7.7)
Requirement already up-to-date: click-plugins in /home/w/venv-osm-borders/lib/python3.6/site-packages (from Fiona==1.7.7)
Requirement already up-to-date: six in /home/w/venv-osm-borders/lib/python3.6/site-packages (from Fiona==1.7.7)
Requirement already up-to-date: munch in /home/w/venv-osm-borders/lib/python3.6/site-packages (from Fiona==1.7.7)
Requirement already up-to-date: click>=4.0 in /home/w/venv-osm-borders/lib/python3.6/site-packages (from cligj->Fiona==1.7.7)
Installing collected packages: Fiona
  Found existing installation: Fiona 1.7.6
    Uninstalling Fiona-1.7.6:
      Successfully uninstalled Fiona-1.7.6
Successfully installed Fiona-1.7.7
w@ubuntu:~/Downloads/tf$ ~/venv-osm-borders/bin/python testfiona.py 
Traceback (most recent call last):
  File "testfiona.py", line 9, in <module>
    for shape in shapes: #this breaks in fiona 1.7.7, works in 1.7.6
  File "fiona/ogrext.pyx", line 1187, in fiona.ogrext.Iterator.__next__ (fiona/ogrext2.c:20124)
  File "fiona/ogrext.pyx", line 210, in fiona.ogrext.FeatureBuilder.build (fiona/ogrext2.c:4387)
ValueError: year 0 is out of range
```

```
w@ubuntu:~/Downloads/tf$ gdalinfo --version
GDAL 2.2.1, released 2017/06/23
```

```
~/venv-osm-borders/bin/python --version
Python 3.6.3
```
Should I expect this test case to pass?

**Comment by snorfalorpagus** [comment] 2018-03-25 16:45
@wiktorn Fiona 1.7.x does not fully support GDAL 2.2. In particular there are issues with the handling of NULL fields. You should either downgrade to GDAL 2.1 or upgrade to the pre-release Fiona 1.8a.
