### ISSUE TITLE
Add methods to list and access multiple datasets within a zip file

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#754] opened 2019-06-01 21:01 UTC
See #753

**Comment by snorfalorpagus** [comment] 2019-06-02 17:03
It looks like `VSIReadDir` can be used to return a list of filenames in zip, or NULL if it doesn't exist. I'm not sure what the API should look like for this.

**Comment by sgillies** [comment] 2019-06-02 18:10
ZipMemoryFile was developed to serve the use case of a single zipped shapefile and its sidecar files, and multiple layers weren't a consideration. I believe we can extend it.

@snorfalorpagus for "ordinary" multilayer datasets we have `fiona.listlayers(path)` and  `fiona.open("path", layer="foo")`. These almost work for an in-memory zipfile, but you need to do some path hacking. Would this be a reasonable API?

**Comment by mostfamiliar** [comment] 2021-09-13 19:35
I'm waiting on listdir() or listlayers() as well ... I tried the suggestions in: https://github.com/Toblerity/Fiona/issues/753 and implemented it roughly the same except my file is an in memory upload:

uploaded = InMemoryUploaded File
```
                zf = zipfile.ZipFile(uploaded)
                names = zf.namelist()
                zf.close()
                regex = re.compile(r'.*\.shp')
                matching = self.match_filename(regex, names)

                with ZipMemoryFile(data["file"]) as zip_file:
                    with zip_file.open(matching[0]) as geo_file:
```
but zip_file.open results in: ERROR 4: `/vsizip/vsimem/cf972137877c410a9fd60388674726ae/cf972137877c410a9fd60388674726ae.zip/Trails_and_Paths.shp' does not exist in the file system, and is not recognized as a supported dataset name.

However:
strangely, if i comment out the ZipFile code i.e. `zipfile.ZipFile(uploaded)` and manually enter the .shp path into `zip_file.open('Trails_and_Paths.shp')` OR i use `zip_file.open()` it works:
<open Collection '/vsizip/vsimem/fac606d715af4501bd7f8a9871c3d23b/fac606d715af4501bd7f8a9871c3d23b.zip/Trails_and_Paths.shp:Trails_and_Paths', mode 'r' at 0x111535d90>

The problem is if file has a nested directory structure it will not open with `zip_file.open()` so I need to specify the path structure. Any ideas on why `zipfile.ZipFile` is causing a weird interaction? Is there something else I need to do besides closing it before I use `ZipMemoryFile`?

**Comment by sgillies** [comment] 2021-12-01 00:29
@mostfamiliar first of all: I'm sorry to be late in replying. The Fiona project is currently blocked by big moves in some related projects (rasterio and shapely) and doesn't get enough attention right now.

So, `zipfile.ZipFile()` takes a "a path to a file (a string), a file-like object or a path-like object." When you pass `uploaded` to ZipMemoryFile, is it a Python file object where we are at the end? It's possible that fiona's ZipMemoryFile assumes we're at the beginning of the file.

**Comment by sgillies** [comment] 2022-12-10 00:30
Fiona's listdir works much better on zipfiles now:

```
>>> import fiona
>>> fiona.listdir("zip://data/data.zip")
['data']      
>>> fiona.listdir("zip://data/data.zip!data")
['collection-pp.txt', 'collection.txt', 'coutwildrnp.cpg', 'coutwildrnp.dbf', 'coutwildrnp.gpkg', 'coutwildrnp.json', 'coutwildrnp.prj', 'coutwildrnp.shp', 'coutwildrnp.shx', 'coutwildrnp.tar', 'coutwildrnp.zip', 'curves_line.csv', 'example.topojson', 'gre.cpg', 'gre.dbf', 'grenada.geojson', 'gre.prj', 'gre.shp', 'gre.shx', 'issue627.geojson', 'LICENSE.txt', 'sequence-pp.txt', 'sequence.txt', '!test.geojson', 'test_gpx.gpx', 'test_tin.csv', 'test_tin.dbf', 'test_tin.shp', 'test_tin.shx', 'test_tz.geojson']
>>> colxn = fiona.open("zip://data/data.zip!data/coutwildrnp.shp")
>>> len(colxn)
67
```

For zipped in-memory files you are, unfortunately for now, required to know how GDAL's /vsizip/ paths work.

```
>>> with open("data/data.zip", "rb") as f:
...     with ZipMemoryFile(f.read()) as memfile:
...         print(fiona.listdir(memfile.name))
...         print(fiona.listdir(memfile.name + "/data"))
... 
['data']
['collection-pp.txt', 'collection.txt', 'coutwildrnp.cpg', 'coutwildrnp.dbf', 'coutwildrnp.gpkg', 'coutwildrnp.json', 'coutwildrnp.prj', 'coutwildrnp.shp', 'coutwildrnp.shx', 'coutwildrnp.tar', 'coutwildrnp.zip', 'curves_line.csv', 'example.topojson', 'gre.cpg', 'gre.dbf', 'grenada.geojson', 'gre.prj', 'gre.shp', 'gre.shx', 'issue627.geojson', 'LICENSE.txt', 'sequence-pp.txt', 'sequence.txt', '!test.geojson', 'test_gpx.gpx', 'test_tin.csv', 'test_tin.dbf', 'test_tin.shp', 'test_tin.shx', 'test_tz.geojson']
```

We've tried to design MemoryFile and ZipMemoryFile so that no one has to think about GDAL's virtual filesystem handlers and are coming up short for listing directory contents. I think we'll probably need to make listdir a method of ZipMemoryFile in a future release.

**Comment by sgillies** [comment] 2022-12-10 01:24
I did add listdir to MemoryFIle.

```
>>> from fiona.io import ZipMemoryFile
>>> with open("tests/data/data.zip", "rb") as f:
...     with ZipMemoryFile(f.read()) as memfile:
...         print(memfile.listdir())
...         print(memfile.listdir("data"))
... 
['data']
['collection-pp.txt', 'collection.txt', 'coutwildrnp.cpg', 'coutwildrnp.dbf', 'coutwildrnp.gpkg', 'coutwildrnp.json', 'coutwildrnp.prj', 'coutwildrnp.shp', 'coutwildrnp.shx', 'coutwildrnp.tar', 'coutwildrnp.zip', 'curves_line.csv', 'example.topojson', 'gre.cpg', 'gre.dbf', 'grenada.geojson', 'gre.prj', 'gre.shp', 'gre.shx', 'issue627.geojson', 'LICENSE.txt', 'sequence-pp.txt', 'sequence.txt', '!test.geojson', 'test_gpx.gpx', 'test_tin.csv', 'test_tin.dbf', 'test_tin.shp', 'test_tin.shx', 'test_tz.geojson']
```

**Closed** 2022-12-13 22:45 UTC
Labels: enhancement
