### ISSUE TITLE
Runtime error with python 3.10.0 - undefined symbol: _PyGen_Send

### ISSUE THREAD

**Issue by Chaz6** [Toblerity/Fiona#1043] opened 2021-10-05 16:01 UTC
Installing using `pip` completes successfully, but trying to use the module fails.

```
>>> import geopandas
>>> world = geopandas.read_file(geopandas.datasets.get_path("naturalearth_lowres"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chaz/.local/lib/python3.10/site-packages/geopandas/io/file.py", line 166, in _read_file
    _check_fiona("'read_file' function")
  File "/home/chaz/.local/lib/python3.10/site-packages/geopandas/io/file.py", line 80, in _check_fiona
    raise ImportError(
ImportError: the 'read_file' function requires the 'fiona' package, but it is not installed or does not import correctly.
Importing fiona resulted in: /home/chaz/.local/lib/python3.10/site-packages/fiona/ogrext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

CentOS 7 64bit
Linux 3.10.0-1160.42.2.el7.x86_64
proj 8.1.1
gdal 3.3.2
fiona 1.8.20
python 3.10.0

**Comment by rbuffat** [comment] 2021-10-05 17:22
@Chaz6 What version of Cython did you use? Does it work when you upgrade to the latest cython available?

**Comment by Chaz6** [comment] 2021-10-05 20:34
I tried using the latest Cython from git master (Cython-3.0.0a9) but again the same problem.

**Comment by Chaz6** [comment] 2021-10-05 20:38
I also tried installing FIona from git master (Fiona-2.0.dev0) but that did not work either.

**Comment by rbuffat** [comment] 2021-10-11 19:39
I currently don't have yet a python 3.10 environment. Based on https://bugs.launchpad.net/lxml/+bug/1904900 it could be something related to Cython. Maybe it is worth a shot trying to [compile](https://github.com/Toblerity/Fiona/tree/maint-1.8#development-and-testing) a clean Fiona maint-1.8 branch (there should be no *.c files).

**Comment by Chaz6** [comment] 2021-10-13 13:59
I tried the maint-1.8 branch, but the result was the same 😢 I am not sure what else to try.

**Comment by shatteringlass** [comment] 2021-11-21 18:08
I'm having a related problem on macOS 12.1:  

```
    ERROR: Command errored out with exit status 1:
     command: /Users/federico/.pyenv/versions/3.10.0/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0w/n2d7fhzj4c513yhfm2ln7l940000gn/T/pip-install-oobw74sa/fiona_d20d8bc75e6744bfac9e9c79c1af676e/setup.py'"'"'; __file__='"'"'/private/var/folders/0w/n2d7fhzj4c513yhfm2ln7l940000gn/T/pip-install-oobw74sa/fiona_d20d8bc75e6744bfac9e9c79c1af676e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0w/n2d7fhzj4c513yhfm2ln7l940000gn/T/pip-record-lnu9hgeh/install-record.txt --single-version-externally-managed --compile --install-headers /Users/federico/.pyenv/versions/3.10.0/include/python3.10/fiona
         cwd: /private/var/folders/0w/n2d7fhzj4c513yhfm2ln7l940000gn/T/pip-install-oobw74sa/fiona_d20d8bc75e6744bfac9e9c79c1af676e/
    Complete output (78 lines):
    /Users/federico/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'metadata_version'
      warnings.warn(msg)
    /Users/federico/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'requires_python'
      warnings.warn(msg)
    /Users/federico/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'requires_external'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-12.1-x86_64-3.10
    creating build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/_loading.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/env.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/compat.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/io.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/drvsupport.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/session.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/inspector.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/__init__.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/logutils.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/crs.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/rfc3339.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/vfs.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/transform.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/collection.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/_show_versions.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/errors.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    copying ./fiona/path.py -> build/lib.macosx-12.1-x86_64-3.10/fiona
    creating build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/options.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/collect.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/distrib.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/env.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/insp.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/cat.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/__init__.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/ls.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/rm.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/dump.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/calc.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/filter.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/load.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/main.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/info.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/helpers.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    copying ./fiona/fio/bounds.py -> build/lib.macosx-12.1-x86_64-3.10/fiona/fio
    running build_ext
    building 'fiona.schema' extension
    creating build/temp.macosx-12.1-x86_64-3.10
    creating build/temp.macosx-12.1-x86_64-3.10/fiona
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/Cellar/gdal/3.3.3/include -I/Users/federico/.pyenv/versions/3.10.0/include/python3.10 -c fiona/schema.c -o build/temp.macosx-12.1-x86_64-3.10/fiona/schema.o
    clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/federico/.pyenv/versions/3.10.0/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/federico/.pyenv/versions/3.10.0/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib build/temp.macosx-12.1-x86_64-3.10/fiona/schema.o -L/usr/local/Cellar/gdal/3.3.3/lib -lgdal -o build/lib.macosx-12.1-x86_64-3.10/fiona/schema.cpython-310-darwin.so
    building 'fiona._transform' extension
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/Cellar/gdal/3.3.3/include -I/Users/federico/.pyenv/versions/3.10.0/include/python3.10 -c fiona/_transform.cpp -o build/temp.macosx-12.1-x86_64-3.10/fiona/_transform.o -std=c++11
    clang++ -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/federico/.pyenv/versions/3.10.0/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/federico/.pyenv/versions/3.10.0/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib build/temp.macosx-12.1-x86_64-3.10/fiona/_transform.o -L/usr/local/Cellar/gdal/3.3.3/lib -lgdal -o build/lib.macosx-12.1-x86_64-3.10/fiona/_transform.cpython-310-darwin.so
    building 'fiona._geometry' extension
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/Cellar/gdal/3.3.3/include -I/Users/federico/.pyenv/versions/3.10.0/include/python3.10 -c fiona/_geometry.c -o build/temp.macosx-12.1-x86_64-3.10/fiona/_geometry.o
    fiona/_geometry.c:13026:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                      ^
    fiona/_geometry.c:13026:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
                ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fiona/_geometry.c:13031:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                      ^
    fiona/_geometry.c:13031:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
                ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fiona/_geometry.c:13115:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                ret = _PyGen_Send((PyGenObject*)yf, NULL);
                      ^
    fiona/_geometry.c:13115:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
                ret = _PyGen_Send((PyGenObject*)yf, NULL);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 warnings and 3 errors generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/federico/.pyenv/versions/3.10.0/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0w/n2d7fhzj4c513yhfm2ln7l940000gn/T/pip-install-oobw74sa/fiona_d20d8bc75e6744bfac9e9c79c1af676e/setup.py'"'"'; __file__='"'"'/private/var/folders/0w/n2d7fhzj4c513yhfm2ln7l940000gn/T/pip-install-oobw74sa/fiona_d20d8bc75e6744bfac9e9c79c1af676e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0w/n2d7fhzj4c513yhfm2ln7l940000gn/T/pip-record-lnu9hgeh/install-record.txt --single-version-externally-managed --compile --install-headers /Users/federico/.pyenv/versions/3.10.0/include/python3.10/fiona Check the logs for full command output.
```

**Comment by rbuffat** [comment] 2021-11-21 19:17
I could reproduce the error on the `python:3.10.0-bullseye` docker image with Cython 0.29.21. Upgrading to a cython version > 0.29.21 seems to work fine.  I needed to upgrade the dev requirements as some seemed to be incompatible with Python 3.10:

Dockerfile:
```
FROM python:3.10.0-bullseye

# Install gdal
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y gdal-bin libgdal-dev && \
    pip install --upgrade pip

COPY Fiona/requirements.txt .
COPY Fiona/requirements-dev.txt .

RUN pip install -r requirements-dev.txt

COPY Fiona /Fiona
WORKDIR /Fiona

RUN python -m pip install --no-deps --force-reinstall --no-use-pep517 -e .

RUN python -m pytest -m "not wheel" --cov fiona --cov-report term-missing
```

Updated requirements-dev.txt:

```
-r requirements.txt
coverage==6.1.2
cython==0.29.22
pytest==6.2.5
pytest-cov==3.0.0
setuptools==59.2.0
boto3==1.20.10
wheel==0.37.0
pytz==2021.3
```

With cython==0.29.21, `docker build` in the directory of the Dockerfile leads to the following error:

```
ImportError while loading conftest '/Fiona/tests/conftest.py'.
tests/conftest.py:13: in <module>
    import fiona
fiona/__init__.py:86: in <module>
    from fiona.collection import BytesCollection, Collection
fiona/collection.py:11: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: /Fiona/fiona/ogrext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

For cython>0.29.21, all tests run successfully.

**Comment by mwtoews** [comment] 2021-11-21 20:04
For the record, the issue with `_PyGen_Send` was discovered with https://github.com/cython/cython/issues/3876 and is fixed as of cython version 0.29.22

**Closed** 2021-11-21 23:01 UTC

**Comment by linzbush** [comment] 2021-12-22 23:18
I am still having similar issues, even after trying to follow the remediating steps above. 

My code
```py
%matplotlib inline

import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point, Polygon
import matplotlib.pyplot as plt

#read in data
bostonCrimeData = pd.read_csv('boston.csv', low_memory=False )
bostonCrimeData
#get geospatial data for Boston
 
street_map = gpd.read_file('City_of_Boston_Boundary.shp')
# street_map.plot()
street_map = street_map.to_crs(4326)
street_map.plot()
```

my DockerFile
```sh
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.205.2/containers/python-3/.devcontainer/base.Dockerfile

# [Choice] Python version (use -bullseye variants on local arm64/Apple Silicon): 3, 3.10, 3.9, 3.8, 3.7, 3.6, 3-bullseye, 3.10-bullseye, 3.9-bullseye, 3.8-bullseye, 3.7-bullseye, 3.6-bullseye, 3-buster, 3.10-buster, 3.9-buster, 3.8-buster, 3.7-buster, 3.6-buster
ARG VARIANT="3.9"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

# [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
# ARG NODE_VERSION="none"
# RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

# [Optional] If your pip requirements rarely change, uncomment this section to add them to the image.
# COPY requirements.txt /tmp/pip-tmp/
# RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
#    && rm -rf /tmp/pip-tmp

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y gdal-bin libgdal-dev && \
    pip install --upgrade pip

# Update C env vars so compiler can find gdal
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal
RUN pip install matplotlib
COPY ./requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt
```

my output

```
the 'read_file' function requires the 'fiona' package, but it is not installed or does not import correctly.
```

I tried changing pyproj, to a lower version but was getting errors. I saw that maybe I should install Fiona first than geopandas, let me know if you have any ideas! Thanks!

**Comment by aspeddro** [comment] 2022-01-30 18:05
Install from github Fiona-2.0.dev0 works for me.

`python -m pip install git+https://github.com/Toblerity/Fiona.git`

**Comment by 5p4r70n** [comment] 2022-06-24 09:09
@aspeddro thanks..
