### ISSUE TITLE
Property named "ID" renamed to "id"

### ISSUE THREAD

**Issue by forman** [Toblerity/Fiona#660] opened 2018-10-28 15:26 UTC
## Expected behavior and actual behavior.

I expect property names to stay as they are when reading features from a GeoJSON file, but a feature property called "ID" is renamed to "id" if the feature contains a key "id".

## Steps to reproduce the problem.

`f1.geojson`:

```
{
  "type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [[66.116068, 9.711914],
       [66.116068, 30.849609],
       [53.252069, 30.849609],
       [53.252069, 9.711914],
       [66.116068, 9.711914]]
    ]
  },
  "properties": {
    "ID": "a9e28096aaa4460fad9bb8264607f805",
    "Sub_Region_Name": "Baltic",
    "Region_Name": "Sweden"
  }
}
```

`f2.geojson`:

```
{
  "type": "Feature",
  "id": "0",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [[66.116068, 9.711914],
       [66.116068, 30.849609],
       [53.252069, 30.849609],
       [53.252069, 9.711914],
       [66.116068, 9.711914]]
    ]
  },
  "properties": {
    "ID": "a9e28096aaa4460fad9bb8264607f805",
    "Sub_Region_Name": "Baltic",
    "Region_Name": "Sweden"
  }
}
```

```
>>> fc = fiona.open("f1.geojson")
>>> f1 = fc.next()
>>> f1["properties"]["ID"]
a9e28096aaa4460fad9bb8264607f805
>>>
>>> fc = fiona.open("f2.geojson")
>>> f2 = fc.next()
>>> f2["properties"]["ID"]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
KeyError: 'ID'
>>> f2["properties"]["id"]
a9e28096aaa4460fad9bb8264607f805
```

## Operating system

Windows 10

## Fiona and GDAL version and provenance

Fiona installed into Python 3.6.7 Anaconda, Inc. using conda default channel

* fiona 1.7.10
* gdal 2.2.2
* libgdal 2.2.2

**Comment by sgillies** [comment] 2018-10-29 14:55
Confirmed @forman.

```
$ fio insp /tmp/f1.geojson
Fiona 1.8rc1 Interactive Inspector (Python 3.6.6)
Type "src.schema", "next(src)", or "help(src)" for more information.
>>> feat = next(iter(src))
>>> feat
{'type': 'Feature', 'id': '0', 'properties': OrderedDict([('ID', 'a9e28096aaa4460fad9bb8264607f805'), ('Sub_Region_Name', 'Baltic'), ('Region_Name', 'Sweden')]), 'geometry': {'type': 'Polygon', 'coordinates': [[(66.116068, 9.711914), (66.116068, 30.849609), (53.252069, 30.849609), (53.252069, 9.711914), (66.116068, 9.711914)]]}}
```

```
$ fio insp /tmp/f2.geojson
Fiona 1.8rc1 Interactive Inspector (Python 3.6.6)
Type "src.schema", "next(src)", or "help(src)" for more information.
>>> feat = next(iter(src))
>>> feat
{'type': 'Feature', 'id': '0', 'properties': OrderedDict([('id', 'a9e28096aaa4460fad9bb8264607f805'), ('Sub_Region_Name', 'Baltic'), ('Region_Name', 'Sweden')]), 'geometry': {'type': 'Polygon', 'coordinates': [[(66.116068, 9.711914), (66.116068, 30.849609), (53.252069, 30.849609), (53.252069, 9.711914), (66.116068, 9.711914)]]}}
```

This is a GDAL issue, however, as Fiona doesn't munge field names like this. The GDAL GeoJSON format driver has some fairly complicated logic around getting feature ids and it looks like it is a little buggy.

**Comment by forman** [comment] 2018-10-29 15:04
Thanks for looking into it!

**Comment by sgillies** [comment] 2018-10-29 15:10
I'm reporting in the GDAL issue tracker now. The field name munging happens even before a feature is read, which should help reveal this bug to the GDAL team:

```
$ fio info /tmp/f1.geojson 
{"driver": "GeoJSON", "schema": {"properties": {"ID": "str", "Sub_Region_Name": "str", "Region_Name": "str"}, "geometry": "Polygon"}, "crs": "EPSG:4326", "crs_wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]", "bounds": [53.252069, 9.711914, 66.116068, 30.849609], "name": "f1", "count": 1}
```

```
$ fio info /tmp/f2.geojson 
{"driver": "GeoJSON", "schema": {"properties": {"id": "str", "Sub_Region_Name": "str", "Region_Name": "str"}, "geometry": "Polygon"}, "crs": "EPSG:4326", "crs_wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]", "bounds": [53.252069, 9.711914, 66.116068, 30.849609], "name": "f2", "count": 1}
```

**Comment by sgillies** [comment] 2018-10-29 15:26
Okay, closing this one. Let's watch the upstream issue for a solution and workarounds.

**Closed by sgillies** 2018-10-29 15:26 UTC
Labels: GDAL/OGR, upstream
