### ISSUE TITLE
Windows wheels

### ISSUE THREAD

**Issue by adamjstewart** [Toblerity/Fiona#1082] opened 2022-03-11 03:27 UTC
Analogous to https://github.com/rasterio/rasterio/issues/513, I would love to see Windows wheels for fiona to simplify multi-platform CI.

**Comment by sgillies** [comment] 2022-03-11 03:32
Duplicate of https://github.com/Toblerity/Fiona/discussions/1073.

**Closed by sgillies** 2022-03-11 03:32 UTC
